### ISSUE TITLE
feature request: resend for bounced mails

### ISSUE THREAD

**Issue by carl-chenet** [Mailtrain-org/mailtrain#1025]
It seems it's not possible today to resend to bounced mails. It would be a great feature in my opinion because SES rate limit sometimes makes lots of emails bounced, for example.

**Comment by bures** [comment]
Makes sense. I think this should be a button in subscription view on a list which would convert all "Bounced" subscribers to "Subscribed". Then I think you could resend your campaign to the list. The subscribers where delivery was successful would not be tried again. (Well, if I remember correctly how it is implemented.) You want to give it a try?

**Comment by bures** [comment]
Well, actually, I might give it a try myself.

**Comment by carl-chenet** [comment]
Was it implemented? was it given up? closing the ticket without explaination or only "I'm cleaning tickets" is a rather strange move. I won't lose time to give feedback if it does not serve any purpose.

**Comment by bures** [comment]
If you look closely, it was consolidated to #1143.

**Comment by carl-chenet** [comment]
Your #1143 links to #793 and I don't read anything about my feature request. Is it somewhere else?

**Comment by forgeOneHQ** [comment]
@carl-chenet , if you look into the Info ticket you see that the it was put into the comment. We have tons of tickets open and this was a feature request. 

Since this is an open source project and on the activity at the moment to implement feature requests a stable team of a few programming it in their free time needs to established. You are welcome to help programming the features you would like to see in mailtrain v2.

At the moment we need to consolidate all issues and get a clear view. I collect it in the #1143 ticket to know where we are, how we can priorize the issues that not just @bures has to deal with it alone and then we can also look how we can implement new features.

My part is taking a look to update all packages to the ,latest version and debug all deprecation warnings to have a good base where we can go on from.

**Comment by carl-chenet** [comment]
no worries, giving you my feedback as a user. I'm also an open source maintainer and I never close a bug report without clear statements about what I'm gonna do with the feedback users gave me. if it's taking into account its great, will happily test the feature if you think it's useful one day.

**Comment by forgeOneHQ** [comment]
@carl-chenet Latest requests that can be from interest I add in #1143 and will investigate together with @bures .

My plan is generate a roadmap out of it and find others to help getting more activity on this. You are welcome to join here.
