### ISSUE TITLE
[Question] Import csv from script

### ISSUE THREAD

**Issue by joker-x** [Mailtrain-org/mailtrain#1077]
I need to import a large csv for update subscribers to a list and another for unsubscribe some mails daily from a bash script that it will run in the same machine of mailtrain. @bures can you help me to choose the better way?

**Comment by PabloCastellano** [comment]
Not sure if I correctly understood your problem.

According to the API documentation inside mailtrain (`MAILTRAIN_HOST/account/api`) you can both subscribe and unsubscribe emails using it.

```
# Unsubscribe
curl -XPOST 'https://MAILTRAIN_HOST/api/unsubscribe/XxXxXxXx?access_token=TOKEN' \
--data 'EMAIL=test@example.com'

# Subscribe
curl -XPOST 'https://MAILTRAIN_HOST/api/subscribe/XxXxXx?access_token=TOKEN' \
--data 'EMAIL=test@example.com&MERGE_CHECKBOX=yes&REQUIRE_CONFIRMATION=yes'
```

Does it help?

**Comment by joker-x** [comment]
We have to sync around 500k subscribers. If we do an api call for all subscribers one by one, will spend too much time.

**Comment by bures** [comment]
@joker-x, I'll be happy to help. I guess you can either create an API endpoint for bulk import or just push it directly to DB. The DB option is in my view a bit complicated because the schema and the columns are not completely straightforward, so would prefer the API route. It will be also more useful for others.

I would not create an API that manipulates the imports (like create import, upload file, run import). In my view it's too complicated and overall the imports are way too complicated. I adopted it from v1, but it was not entirely the smartest choice.

Instead, I would propose API that allows you to submit a batch of rows (like in the CSV file when doing import) and execute the basic subscribe/basic unsubscribe operations (like the are in the Import UI). Essentially the post could somehow look like:
```
{
  subscriptions: [{...}, {...}],
  listCid,
  operation: "basic_subscribe"
}
```

If there are too many subscriptions, you would repeat the post with smaller batches (e.g. 1000 subscriptions at a time).

The logic needed for this is here: 
- https://github.com/Mailtrain-org/mailtrain/blob/40881c8c7907854651ff592e5337891da0f75af7/server/services/importer.js#L187 
- https://github.com/Mailtrain-org/mailtrain/blob/40881c8c7907854651ff592e5337891da0f75af7/server/services/importer.js#L286
- https://github.com/Mailtrain-org/mailtrain/blob/40881c8c7907854651ff592e5337891da0f75af7/server/services/importer.js#L335

We could move the respective pieces of code to server/lib and reuse it in the importer and in this import API. I would like to reuse the handler functions and the way they deal with DB, so that we have consistent behavior both through UI and the API. 

Also, at some point I would like to introduce "sync" functionality that will allow you to synchronize lists (e.g. to sync subscriptions, unsubscriptions, etc.). The goal is to be able to have a hierarchy of lists where for instance the parent comprises all subscribers in the children lists. It's kind of an alternative to list segments, but more powerful because you can assign individual rights to the lists. Also, the list determines how it gets presented to the user through the subscription form, etc.

Please let me know if you would like to take up the task of creating the API, like I suggested above. I'll be happy to assist you should you run in trouble.

**Comment by joker-x** [comment]
@bures i was fired for the company where i would want to replace sendy for mailtrain. This is the reason for i could not implement this improvement. But, al least, i would like to give thanks for your response and your right technical criterial :)

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
