### ISSUE TITLE
Provide tagged docker images?

### ISSUE THREAD

**Issue by maxnoe** [Mailtrain-org/mailtrain#1101]
Hi, thanks again for this great piece of software.

I just saw you made a new tag (the first for v2, yeah!).

For better reproducibility / avoiding surprise, could you publish corresponding tagged docker images? So a `mailtrain/mailtrain:v2.20210609.0-1` ?

https://hub.docker.com/r/mailtrain/mailtrain/tags?page=1&ordering=last_updated

**Comment by dlecan** [comment]
Yes, I need this!
Thank you

**Comment by PhilippeAccorsi** [comment]
That is a good request :)

Latest is good but its not really usable on production because we need to have solution to deploy again same version if necessary on a new server.

One solution I use for the moment is to pull the latest version and use this command locally 
~~~
docker tag mailtrain/mailtrain:latest mailtrain/mailtrain:v2-2021-06-09
~~~
, so on my server I can make sure I always use the good version.

It is possible to move this image on another server by using 
~~~
docker save -o /tmp/mailtrain-v2-2021-06-09
~~~
and copy image by network with rsync or scp, and after that using 
~~~
docker load -i /tmp/mailtrain-v2-2021-06-09
~~~
But this is not the easy way.

**Comment by bures** [comment]
I'll be glad to do it. But do you have any suggestions how to automate this? At the moment, the images are built automatically when something is pushed. This is automated on the dockerhub side. Thanks.

**Comment by maxnoe** [comment]
You can setup automated builds for tags https://docs.docker.com/docker-hub/builds/#tag-and-branch-builds

**Comment by bures** [comment]
I manually built the docker image for v2.20210609.0. Also, I set up automatic builds for subsequent releases. Let's see if it works once we create another release. Thanks.

**Comment by omercnet** [comment]
seems automated builds aren't working, latest release does not match main
