### ISSUE TITLE
anonymize user data while tracking, like IP not storing in database

### ISSUE THREAD

**Issue by jonathanmmm** [Mailtrain-org/mailtrain#1135]
Hi,

is it possible to anonymize the IPs stored in the database?
Right now with this way I can clearly see which user accessed with which device, from which IP and which exact links he opened how many times. Same with Country, Device and which exact links are opened by a specific user (subscriber).

This doesn't seem GPDR compliant.

Is there a way to track such data and still make them impossible to track them back to an individual user. I know that right now you can only see which user opened the email, but with the help of the database you can see all this information.

**Comment by bures** [comment]
If you don't want this information to be stored, just disable the tracking for the campaign. The IP address is not something sensitive. It's the user identity that is.

**Comment by jonathanmmm** [comment]
@bures 
I know I could deactivate it.
But right now it seems to me that nobody could use the included tracking living or serving people in Europe. 

GPDR means storing the least information necessary, also with tracking. And IP address is an information sensitive, like phone number.
I propose to anonymize it (like the last part) and anonymize who opened an email. For the ip part I know it should be changed, the other thing I don't know if this is necessary to comply to GPDR.

Could this be an enhancement proposal?

**Comment by bures** [comment]
When you use tracking, you are already dealing with personal information because you associate an email address (i.e. personal identifier) with the information (a) whether it accessed a campaign, (b) when it accessed the campaign, (c) from which type of device, and (d) from where it accessed the campaign.

If you drop or anonymize IP addresses, you are essentially stopping to associate the information about geographical location with a particular email address. You are still left if (a)-(c). 

So what I'm saying: Yes, you can certainly enhance Mailtrain to drop/anonymize IP addresses, but that's not gonna solve your GDPR problem in its entirety. You would still have to inform the subscribers that you are collecting personal information regarding if, when and how they opened the campaign.

**Comment by jonathanmmm** [comment]
Thats true, a GPDR mode would be the best, where every subscriber email that is sent creates unique links for that subsricer. But these are not linked to a subscriber after the campaign is sent.
That way you can see that an non identifable subscriber from IP 92.14.x.x opened via Phone these three links.
That way you have knowledge which links work on which phone, in which countries and such, but you can't trace one collected dataset back to a particular subscriber.

What do you think?
Right now you can identify them through a subscriber number (starting with 1), if you just unlink them, you have the same information except anomyized IP addresses and no idea who opened this link 30 times from French on a Desktop.

**Comment by bures** [comment]
Yes. That could work. But it would require rather bigger changes in handling the campaign messages. I'm afraid, this is not on my radar. So if anyone wants to do it. I'll be happy to help with an advice and merge it if it has sufficient quality.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
