### ISSUE TITLE
Sending rate degradation

### ISSUE THREAD

**Issue by misterioss** [Mailtrain-org/mailtrain#1163]
Hi,

when we have around 900 000 emails sent I see gradual degradation of sending rate. At the start, it's around 300 per second and becomes lower and lower over time. On the screen below you may see CPU utilization for one campaign.

**Server** CPU utilization:
![screen_shot_2021-11-05_at_16 17 56](https://user-images.githubusercontent.com/3921977/140524872-aa7745d5-deb5-4e09-b587-2a146243df29.png)

**Database** CPU utilization:
![screen_shot_2021-11-05_at_16 19 15](https://user-images.githubusercontent.com/3921977/140525058-c37974ca-a7a3-4f7e-bf59-9f3e0cf6a408.png)

Any ideas where to look?

**Comment by nostradam** [comment]
Could it be because your server is receiving errors and compounding them ? For example deferred messages ? I use graylog to be able to monitor that and your graph is the exact opposite of my deferred graph. Maybe you are at your maximum capacity and that capacity decreases as you receive the deferred messages that have to be processed.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
