### ISSUE TITLE
Stats issues with SparkPost

### ISSUE THREAD

**Issue by rhbkweb** [Mailtrain-org/mailtrain#122]
Hi,

Already made a new and clean installation of Mailtrain and now the external SMTP with SparkPost is working… but with 3 issues that I leave bellow:

a) Complaints are not working. 
I try to send 2 email newsletters to a Gmail account and clicked on “Report as Spam”. On Mailtrain in the campaign report it still shows 0 Complaints.

b) Clicks are not working. 
On the default template I added a URL Link and then send an email newsletter just to 2 emails (one in Gmail and other in ZOHO). After received the emails I clicked on the link and also on the View in browser. On Mailtrain it still shows 0 Clicked.

c) Bounces are working with problems. 
I send 2 emails to non existent email accounts and Mailtrain just reported one Bounce. The bounce that was registered on Mailtrain is a non-existent Gmail account (efdhdw38923742389ehd2udnh2839jdfg3209###@gmail.com). The bounce that was not registered was sent to a non existent domain (dfiiofnm##$d1em@dijwemwopefjreopw.com)

--
In terms of Unsubscribed and Opened stats, they seem to be working perfect!

Can you please verify this from your end to confirm if its a bug from Mailtrain or some bad configuration on my end? If from my end you need any further information, just ask me. 

P.S. Great software you have here! Thanks

**Comment by andris9** [comment]
Do you have the [webhooks](https://github.com/andris9/mailtrain/wiki/Setting-up-Webhooks-for-SparkPost) set up?

**Comment by rhbkweb** [comment]
About the "Clicks not working" it was my mistake. I had in SparkPost > Account > SMTP Relay > Engagement Tracking > Disable. I have enable this setting and now Mailtrain already register the clicks.

Anyway it just counts the clicks on a image link, because is still not counting the url clicked links.

**Comment by tuck1s** [comment]
Hi @rhbkweb, I'm a MailTrain beginner. However I have MailTrain v1.23.2 installed on Ubuntu 16, sending messages thru SparkPost, and the open/click tracking works for me. I wanted to share some info about the SparkPost setting you mention above.
That will control whether _SparkPost_ applies its own wrapping to URLs in your mail body.  If you look at the raw mail <A HREF ..> you will see SparkPost wraps those links, allowing SparkPost to count opens/clicks in its Web UI.  However MailTrain has (unless you disable it in settings or campaign) already wrapped those links itself.
Both MailTrain and SparkPost use http 302 redirects for this.  Here's an example of a double wrapped link I sent. You'll notice the `spgo.io` link is quite long, that's because SparkPost encodes a lot of data in there, including campaign ID, metadata etc.

`http://spgo.io/f/a/BXHo7bVrtqiRlR2M6dFPhg~~/AAAM_AA~/RgRbLP3eP0EIACyln4DaTsNXA3NwY1gEAAAAAFkGc2hhcmVkYQdoZWxsb181YAw1Mi4zOS41MS4xODRIHUhKTFZxSEZtWi5Cay1UdVN0WFcuU3lWMGRydFhXQgoAAF7KS1lVE4bFUhhzdGV2ZS50dWNrQHNwYXJrcG9zdC5jb20JUQQAAAAAREtodHRwOi8vbWFpbHRyYWluMi50cnltc3lzLm5ldC9saW5rcy9ISkxWcUhGbVovQmstVHVTdFhXL1N5VjBkcnRYVy9TMThQOVN0bWJHAnt9` 302-redirects to:

`http://mailtrain2.trymsys.net/links/HJLVqHFmZ/Bk-TuStXW/SyV0drtXW/S18P9Stmb` 
which in turn 302-redirects..

If you don't use SparkPost's UI, you could turn off SparkPost's engagement tracking.
In theory, future MailTrain could use SparkPost's webhooks feed to get opens/clicks, but @andris9 has already built the mechanism and it's SMTP-provider-agnostic. 

Hope this helps.

**Comment by forgeOneHQ** [comment]
I am closing this issue since it is v1 related. if you want you can test it with v2 and let us know if you have any issues with it.
