### ISSUE TITLE
SMTP setup

### ISSUE THREAD

**Issue by Louisias** [Mailtrain-org/mailtrain#1286]
Hi All,
I have installed the docker V2 mailtrain version.
I want to use the postfix service installed on my server to send my mailings.
In mailtrain I have been trying to setup a generic smtp but it does not work

![2022_08_10_18_11_19_Mailtrain_Mozilla_Firefox](https://user-images.githubusercontent.com/15248697/183960090-b12ff5dc-04da-4e12-ad16-0f6b386ddb63.png)

I have no problems sending emails from the server with the "mail" command  and I believe the docker setup might be incorrect (port binding missing ....).

Could someone advise please.
Many thanks,

**Comment by saschafoerster** [comment]
Maybe try it with "host.docker.internal" instead of 127.0.0.1 and the following configuration, if you want to reach to host from inside a docker container (as right now you are trying to use port 25 of the docker container, not the host): 
https://medium.com/@TimvanBaarsen/how-to-connect-to-the-docker-host-from-inside-a-docker-container-112b4c71bc66

**Comment by Louisias** [comment]
Hi Sascha,

Thank you for your help.

I think I have solved y problem in a different way:

1. I have added the public ip address of my server in the mailtrain config:
![image](https://user-images.githubusercontent.com/15248697/184075916-04ec8060-1e13-4b43-ba12-da599d845fbe.png)

2. I have modified postfix so that connections from the container's IP are not rejected:
mynetworks = 172.20.0.0/16 , 127.0.0.0/8

I still have a few issues with this version of mailtrain but I'm hoping to get it to work....

Best !
