### ISSUE TITLE
docker-compose gives me blank page

### ISSUE THREAD

**Issue by ygit1** [Mailtrain-org/mailtrain#1316]
```docker-compose up ```

seems succeeded everything works well,
but go to mydomain.com:3000, nothing shows up, just blank white page appears.

ubuntu 18.04
mailtrain v2

before v2 I could setup with docker-compose without hassle...

**Comment by paolomarr** [comment]
Same symptoms here, using Apache proxypass on default mailtrain port 3000.
```
ProxyPreserveHost On
ProxyPass / http://localhost:3000/
ProxyPassReverse / http://localhost:3000/
```

If I open the browser's developer console I can see that the main html page is being loaded ok, but all of the css/js in the <head> tag have as host in their link localhost:3000, instead of the public host's URL:

<img width="607" alt="Screenshot 2023-02-14 at 00 01 04" src="https://user-images.githubusercontent.com/12608842/218593817-d08a5720-5e93-49c1-89c6-c6cb5818bd80.png">

It already happened months ago. Then I just deleted the mailtrain docker image and issued a `docker-compose up` again and it got back working

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
