### ISSUE TITLE
Bounces should be splittable as hard/soft

### ISSUE THREAD

**Issue by heroic** [Mailtrain-org/mailtrain#182]
It's not possible to see how many hard vs soft bounces happened in a campaign. This is primarily helpful to see if the content is bad or not.

AWS does support splitting these, but I am not sure about other services. @andris9 Do you have plans to add this? I am not sure if adding a column to the sql would break things, and hence I am not picking this up until a discussion is done.

**Comment by andris9** [comment]
This is not planned. If you want to work on this it would be great.

SQL upgrades in Mailtrain are not rockect science, what you would need to do is to create an upgrade script to [setup/sql](/andris9/mailtrain/blob/master/setup/sql/) folder like [this one](https://github.com/andris9/mailtrain/blob/master/setup/sql/upgrade-00010.sql) that adds new column to every `campaign__X` table. See the [upgrade script template](https://github.com/andris9/mailtrain/blob/master/setup/sql/upgrade-template.sql) for details.

You would also need to edit [meta.json](/andris9/mailtrain/blob/master/meta.json) and set the latest schema version to use. Once you start Mailtrain it picks up the latest upgrades and applies these to the database (do not add the columns manually, otherwise the upgrade would end with a conflict error and Mailtrain would not start). There is currently a Pull Request open that adds a new upgrade script with index 22, so you could use 23.
