### ISSUE TITLE
Dropdown field type that is mapped to a single column in imported CSV

### ISSUE THREAD

**Issue by bures** [Mailtrain-org/mailtrain#217]
As far as I understand the dropdown field type, a single column in a CSV file cannot be easily mapped to a selection of a Dropdown field type. This is because Mailtrain represents the different options as separate fields, which are then grouped and displayed together through the grouped field. However, in the CSV file, one would need an extra boolean column for each option in the Dropdown.

Am I correct? Or am I missing anything?

If my understanding it correct, I believe it would be a nice addition to allow for additional field types "non-grouped Dropdown", "non-grouped Radio button". 

These could have textual configuration similar to Drupal radio buttons:

```
nl|The Netherlands
be|Belgium
fr|France
```
In the database, the field value would the id (e.g. "nl"). The same would be used when importing the CSV file.

I will probably need such functionality soon to represent countries, regions and roles of the subscribers within a non-profit organisation.

What do you think?

**Comment by andris9** [comment]
Currently the only way for importing dropdowns would to have a separate column for every possible option, so if you want to use country lists with 200 different options then yes, the current importer can be quite difficult to use. One solution would be to use the merge value that every field has, so you could match merge tag values against the CSV dropdown column to select proper value.

I guess though that the proposed solution would be good enough as well but in this case you would loose segmentation based on dropdown value or you would have to change how segments work as well.

**Comment by andris9** [comment]
Yeah, I never considered long lists. You can't even do this for now because every field and value is mapped to a separate column in the database. So if you have a list of 200 elements it would mean 200 boolean columns in MySQL. It's not even possible to use so many indexes.

It would probably make a lot of sense to change this, as you described, at least for Dropdowns to use a single column with the selected key as value instead of mapping every separate option to separate column. Current system works really well with Checkboxes where you can have multiple combinations but Dropdowns are a bit different.

**Comment by bures** [comment]
Perfect. Thanks. Agreed.

**Comment by jonasob** [comment]
Interestingly, in the FSFE, we've touched upon exactly the same need. I see you worked a bit on this in August, @bures. The change described with a single column for dropdown selects make a lot of sense to me, so we'd be eager to see this too.

**Comment by bures** [comment]
It will be a part of a rather big update that I'm working on. However, judging my progress and also the amount of work in my daily job, I assume it will take a few more months before it can be released with the rest of the things.
