### ISSUE TITLE
User management with granular permissions

### ISSUE THREAD

**Issue by bures** [Mailtrain-org/mailtrain#223]
I should be finished a pull request for #218, #219, #220, #221, #222 ready in a few days. After that, the next on my list of features I would like to implement for Mailtrain is the user management with granular permissions. I though that it would be good to have a discussion now about what features exactly are we looking for and what the requirements are.

(By user management I mean here users natively managed by Mailtrain, not the integration through LDAP.)

Here a proposal to discuss:

As far as my understanding goes the system supports multiple users in the backend (database, login, forgot password). It does not have support (in views, models and router) to do CRUD operations over users. Further, it does not have any notion of user permissions. Currently, every user is an admin.

I believe we should be able to limit user privileges per domain objects (lists, campaigns, etc.). I would suggest similar approach that GitLab has. It recognizes a few coarse-grained permission levels (reporter, developer, master) per project (i.e. the domain object). A user that creates the domain object becomes it's master/owner and can share it with other users (always specifying what permission level should be used when sharing).

Gitlab further offers groups - each group defines a namespace to which domain objects belong. A user can become a member of a group and be given permission level in the group (i.e. reporter, developer, master). The permission level a user has in the group applies to all objects in the group.

In our case, the situation is a bit more complicated because we have more types of domain objects and consequently larger variety of permissions (I tried to provide an initial list of fine-grained permissions below).
 
Obviously, the coarse grained permissions make it easy to share, because when sharing a user simply selects among 2-3 options (e.g. reporter, developer, master). On the other hand, they limit the the flexibility because they prescribe a certain process (for instance: Can maintainer send to the list? Or should there be another level to send to a list?).
 
As a solution taking the best from both the worlds, I would suggest that we make the coarse-grained permission levels configurable in the config files. We internally define fine-grained permissions (somehow as they are below) which are used inside the code. Then in the config, we group them to coarse-grained permissions attached to a domain object (an example of coarse-grained permissions is given at the end). 

At the moment, I would not consider the groups/namespaces (similar to what GitLab has). If we keep the scheme above, they can be added at any later point of time. It would just mean that a domain object is created within a group/namespace, thereby being automatically shared with all users in the group/namespace at their respective permission levels.

What do you think?

@andris9, @witzig - I would need especially your opinion. If we can reach an agreement in a couple of days, I believe I could start implementing it somewhen later this week (or on the weekend). As I wrote above, I would probably need only a few more days to finish the extension of the subscription process and issue the pull request. After than, I would like to dedicate my spare time to the user management. Thanks.

___
#### Proposal of fine grained permissions 
_List (permission per a particular list)_
- use the list in campaign edit
- view the list
- maintain the list (CRUD operations over subscribers in the list + import into the list)
- administer list's segments
- send to the list
- administer the list (all above plus Edit list, Delete list and anything in Custom forms for the given list)

_Lists (global permissions)_
- create a new list
- administer lists (all permissions for any list)

_Template (permissions per a particular template)_
- view the template
- edit the template
- delete the template

_Template (global permissions)_
- create a new template
- administer templates

_Campaign (permissions per a particular campaign)_
- view the campaign
- edit the campaign
- reset campaign
- delete the campaign
- view campaign's stats
- send the campaign (the user has to have corresponding "send to the list" permission)

_Campaigns (global permissions)_
- create a new campaign
- administer campaigns

_Automation (permissions per a particular trigger)_
- administer the trigger (the user has to have corresponding "view the list", "view the campaign", "view campaign's stats", and "send to the list" permissions to make the selection in trigger editing window)

_Automation (global permissions)_
- create a new trigger
- administer triggers

_Report (permissions per a particular report)_
- view/download the report
- re-run the report, stop the report, see report's stderr
- administer the report (edit its parameters, delete)

_Reports (global permissions)_
- create a new report
- administer reports

_Report template (permissions per a particular report template)_
- use the report template (during create a report and administer the report)
- administer the report template

_Report templates (global permissions)_
- create a new report template
- administer report templates

_User management_
- administer users (includes CRUD over users, assign global permissions to users, revoke permissions to domain objects)
___

#### Example of coarse grained permissions (configurable with Mailtrain config)
_List object_
- Maintainer
    - view the list
    - use the list in campaign edit
    - maintain the list (CRUD operations over subscribers in the list + import into the list)
    - administer list's segments
- Maintainer with send    
    - all above
    - send to the list
- Master
    - all above
    - administer the list (all above plus Edit list, Delete list and anything in Custom forms for the given list)

_Campaign object_
- Editor
    - view the campaign
    - edit the campaign
- Master    
    - reset campaign
    - delete the campaign
    - view campaign's stats
    - send the campaign (the user has to have corresponding "send to the list" permission)

_Global permissions (associate with a user)_
- Campaign creator
    - create a new campaign
- Master creator
    - all above
    - create a new list
    - create a new template
    - create a new trigger
    - create a new report
- Administrator
    - all above
    - create a new report template
    - administer lists
    - administer templates
    - administer campaigns
    - administer triggers
    - administer reports
    - administer report templates
    - administer users

**Comment by andris9** [comment]
The problem with current design of Mailtrain is that you can only do permission filtering in the beginning of the request because the user context is not passed down to the lower level functions.

So this can be done right now:

```javascript
router.all('/create-new', (req, res, next) => {
    if (!check_user_permissions_somehow(req.user)){
        return next(new Error('Only admins can do this');
    }
});
```

But this can not be done, at least without some modifications how methods are called because the called function does not know about the surrounding request context:

```javascript
// segments.js
module.exports.create = (listId, segment, callback) => {
    if (!check_user_permissions_somehow()){
        return callback(new Error('You do not have permissions to update segments'));
    }
};
```

I guess though that most checks can already be done in the router level so individual methods might not need to know anything about permissions. Templates need to be updated accordingly as well - if an user can not do something then the option to do so should not be visible either.

**Comment by bures** [comment]
That's a good point. I have not realized that we can't easily have a global session object (like in PHP). 

Well we could always pass the context explicitly - i.e. module.exports.create = (req, listId, segment, callback) => { ... }

But what about this: https://github.com/othiym23/node-continuation-local-storage
or this (https://www.npmjs.com/package/request-local), which is just supposed to be only a small wrapper around the continuation local storage.

Or any other ideas?

**Comment by andris9** [comment]
I'd go with passing context to underlying functions:

```javascript
router.get('/', (req, res)=>{
    let ctx = {req, res};
    doSomething(ctx, other, arguments);
});
```

`req` and `res` might not always be available though, for example when the function is invoked from an internal service like the sending queue processor etc.

**Comment by bures** [comment]
Makes sense. Let's construct the context like this and pass it around. I would additionally put there "user" object or something similar to have it available even when called from internal services.

**Comment by bures** [comment]
First of all, sorry for the slow progress. I was a but busy in the work. Now it should be better. 

So far I created the namespaces and user management UI through ReactJS and Knex. It does not provide any permission assignment yet. Only CRUD on users and namespaces. (It in my repo on Github)

Now I started to do integrating with related existing features in Mailtrain. In particular, I would like to port port the login/logout features to the Knex-based (async/await) users model including the LDAP-based authentication. Further, I would like to adjust the user management UI to behave differently when LDAP is enabled (to disallow the change of attributes managed through LDAP).

Once I'm finished with this one, I would like to start working on the permission management.

Now, the question:
Do you have any way to test against LDAP (e.g. some LDAP docker container, or simple to spin up instance with the right configuration or some test users, anything...). I just don't want to spend too much time configuring an LDAP server just to be able to test that my refactoring did not break anything.

Thanks.

**Comment by andris9** [comment]
You could try to use the testserver provided by the original LDAP pull request: https://github.com/Mailtrain-org/mailtrain/pull/85#issuecomment-242348302

**Comment by bures** [comment]
Perfect. Thanks. I'll give it a try.

**Comment by bures** [comment]
I just committed in my Mailtrain's repo (branch access - https://github.com/bures/mailtrain/tree/access) the access control feature for reports and report templates. It somehow completes the efforts so far.

It consists of the following:
- User management (both for local authentication and LDAP-based auth)
- Namespace management
- Sharing of reports, report templates and namespaces
- User roles
- Controlled access to all above
- All this in the React-based client for endpoints /account, /users, /reports, /namespaces. The login, forgotten passwords, etc. are also handled through the React-based client

Some brief description of the concepts that the access control relies on can be found in https://github.com/bures/mailtrain/blob/access/access-control.md

I believe this gives a good example how the new client and access control could work.

It would be helpful if you could take a look. If you like it, it would be now necessary to go on and turn the rest of Mailtrain to the new client (which also means work on the server side because it requires new rest endpoints and possibly some rewrite here and there to the promise-based interface). Any feedback is of course welcome.

If you are OK with it, I would start turning the Lists menu item to the React-based client (plus modification on the server). 

Thanks. T.

**Comment by witzig** [comment]
Wow! You've been hard at work there. And the whole concept seem very prudent to me. 👍 

Gave it a quick spin and stumbled upon a bug, see pictures:

![01](https://user-images.githubusercontent.com/4999980/28694848-1ae6ffda-732c-11e7-8153-192e04e2b7a0.png)
![02](https://user-images.githubusercontent.com/4999980/28694849-1b06c14e-732c-11e7-82ef-42007001e905.png)
![03](https://user-images.githubusercontent.com/4999980/28694850-1b0d2b56-732c-11e7-8270-0ff79942fcaa.png)

Also the delete button for the Global namespace in the user "Shares" view should probably be hidden. The Global namespace seems generally a bit confusing if the docs weren't read. Since every namespace is within the Global NS (according to the UI), one would initially assume that this applies too:

> [...] sharing a namespace amounts to giving access to all entities within the namespace and transitively in all child namespaces.

- - -

> If you are OK with it, I would start turning the Lists menu item to the React-based client (plus modification on the server).

Your work is very much appreciated, so certainly no objections form my side. :-)

**Comment by bures** [comment]
Hello Roger. 

Thanks a lot for your prompt feedback. Very appreciated. It's very helpful that I can test on you the intuitiveness and explanation of the concepts. 

I removed the delete option from the automatically assigned shares. I also extended a bit the description of the access control based on my understanding of feedback. I'll commit it in the afternoon, once I'm back at my computer.

As for the bug, I'm not exactly sure if I understand why is it a bug. I suspect my description of the access control created some confusion.

Essentially, a user has access only to the things that have been shared with him/her. Unless the root namespace ("Global") is shared, he/she does not have access to it.

The global user role (the one shown in Users) can automatically share the root namespace and the namespace of the user. The master role gives master access to the root namespace irrespective of the namespace of the user. The namespace of the user here has still meaning if there are a lot of users and one uses namespace to organize them (pretty much like in LDAP or AD). In default.toml there is an example of "editor" role. It gives "editor" access to the namespace where the user is located. That I believe would create the behavior you expected. 

Or did I completely misunderstand?

In any case, the low level configuration of roles is a bit complex. It would be good if we could come up with some sensible default definition of roles. Then, if anyone has more specific needs, they can customized in the config. Do you please have any suggestion what the roles shipped in the default config should be?

Maybe we could even have interactive installation script that asks you whether you want simple deployment (i.e. only a few users who are all admins), or whether you want different roles and namespaces.

In case of the simple deployment, we could hide the configuration of namespaces and always assume the root namespace. It would be all there, just not shown so as not to confuse the user. If one needs a more complex case, the namespaces could be unhidden in the configuration.

What do you think?

Thanks a lot. It will be great if we could give it together some sensible shape. I'll continue now with the lists. It's gonna be quite some work. :-)

**Comment by witzig** [comment]
> As for the bug, I'm not exactly sure if I understand why is it a bug.

I created 2 namespaces `ns-one` and `ns-two`, and 2 users `ro` and `pe`.

`ro` has been made a `Master` of `ns-one`.
`pe` has been made a `Master` of `ns-two`.

The users view shows their namespaces correctly:

- - -

![01](https://user-images.githubusercontent.com/4999980/28708828-f29b1a00-737d-11e7-8d1b-a3e24d4283a0.png)

- - -

Also the user edit view shows the namespace correctly:

- - -

![04](https://user-images.githubusercontent.com/4999980/28708871-1d86bc7e-737e-11e7-8c33-3df852296c47.png)

- - -

![05](https://user-images.githubusercontent.com/4999980/28709388-6b3fe1a0-7380-11e7-9607-63c7910e612d.png)


- - -

The user "Shares" view for `ro` however shows `ns-two` instead of `ns-one`:

- - -

![02](https://user-images.githubusercontent.com/4999980/28709087-00752502-737f-11e7-8f29-8d4d68a6bb64.png)

- - -

The user "Shares" view for `pe` does not list `ns-two`, only the Global NS:

- - -

![03](https://user-images.githubusercontent.com/4999980/28709208-a3268430-737f-11e7-8134-28594b95f571.png)

- - -

Granted there was some clicking involved and I don't remember when it ended in this state exactly. Guess I could reproduce if needed. :-)

- - -

> Do you please have any suggestion what the roles shipped in the default config should be?

I'll make some time this evening, yet this is probably a thing we should have broader input. And a quick feedback from @andris9. :-)

**Comment by witzig** [comment]
Thanks, Tomas. I was a bit slow there, sorry.

Before I started testing, I purposely _skimmed_ through the docs/config and started toying around, as that's what most users will do. Or so I assume. ;-)

> The global user role (the one shown in Users) can automatically share the root namespace and the namespace of the user.

Perhaps roles which automatically share the root namespace should be named differently, say "Super Master". Otherwise I think it'd be more expressive if the root namespace has to be shared explicitly.

As for the default roles, I'd suggest to keep it a simple as possible. We can extend it anytime without problems, but removing a role which has proven confusing or even unnecessary would require a db migration and also trigger some tickets.

Taking some inspiration from WordPress (which roles seem to work for many publishing houses and lots of people are familiar with them) :

- Super Admin – somebody with access to the site network administration features and all other features.
- Administrator – somebody who has access to all the administration features within a single site.
- Editor – somebody who can publish and manage posts including the posts of other users.
- Author – somebody who can publish and manage their own posts.
- Contributor – somebody who can write and manage their own posts but cannot publish them.
- Subscriber – somebody who can only manage their profile.

I'd naively compare:

- an MT `Administrator` with the WP `Super Admin`. All permissions.
- an MT `Master` with the WP `Administrator`. Anything under their own namespace.
- an MT `Editor` with the WP `Editor`. Anything under their own namespace related to an editors task, including sending.
- an MT `Author ` or `Campaign creator` with the WP `Contributor `, i.e. a WP `Author ` without publishing rights.

Taking my use case as an example: A small publisher with 10+ brands (namespaces) under the same roof. Each of these brands has a dedicated Editor and Art Editor. The Art Editor creates the campaign based on the Editors 'input', obtains final approval, then the campaign gets scheduled. This fits acceptably into the WP user roles, at least in theory.

However, this isn't a large organisation like yours, thus what I roughly laid out might not even overlap with your use case.

So, in fact, I think you've probably nailed the default roles already:

- Administrator - somebody who's responsible for the whole installation
- Master - somebody who has all permissions in the namespace
- Editor - somebody who's primarily responsible for the 'content' in the namespace 

The only thing I'd shape a bit differently are the permissions of the Editor, but I need to think about that some more.

> Maybe we could even have interactive installation script that asks you whether you want simple deployment (i.e. only a few users who are all admins), or whether you want different roles and namespaces.
In case of the simple deployment, we could hide the configuration of namespaces and always assume the root namespace. It would be all there, just not shown so as not to confuse the user. If one needs a more complex case, the namespaces could be unhidden in the configuration.

Yeah, that would be nice to have if it doesn't overly complicate the codebase. But I don't think it's really necessary if we keep the default roles few and simple. And unless a namespace has been created, there's only the root namespace to choose from anyway.

Maybe we could also start a collection with role configs in the Wiki, then extend the default roles over time with those proven essential ...

Thanks again, Tomas. I'll put some more thought into it.

**Comment by bures** [comment]
Hello Roger.

Thanks a lot and no apologies. I'm happy for your critical feedback. You did what most people will do. We really a should not create confusion by naming. Once it all gets implemented and w bit more stable in naming and phrasing, I would be very happy if you could go through it all and suggest changed in the UI and messages to make it all more intuitive. 

I very much like your proposal. The roles Administrator, Master, Editor, Author/Campaign creator sound perfect to me.

The idea with wiki is good too. We'll need some experience with it once it is implemented, but this is definitely a good structure to start with. It would fit very well my case too.

Thanks.

**Comment by mauricemeyer** [comment]
Is there progress here? Anything I could do to help out?

**Comment by kusaasira** [comment]
Any progress on the user management? Because I cannot see this feature with the latest Mailtrain. Only one user admin which is a limitation.

**Comment by bures** [comment]
This feature is present in Mailtrain v2 beta.

**Comment by kusaasira** [comment]
Is the v2 beta on the Master?

**Comment by bures** [comment]
Nope. It's the development branch.

**Comment by kusaasira** [comment]
@bures Cannot see it on the development branch

**Comment by bures** [comment]
You mean you installed it and don't see it in the UI? It's under Administration -> Users. The different types of roles have to be setup in the server/config/production.yaml (similar to server/config/default.yaml) based on your particular needs.

**Comment by kusaasira** [comment]
Okay. Like I switched to the development branch. After updating to v2.  

The v2 works very fine.

When trying to switch to the development branch, My whole UI gets messed like the assets do not load. Is there any further configurations to rectify this or I skipped something?

**Comment by bures** [comment]
You cannot just switch to development branch. You have to do a new install. See https://github.com/Mailtrain-org/mailtrain/blob/development/README.md

**Comment by kusaasira** [comment]
Okay. Apologies for the many questions but this point here aint well expounded.

> Run the installation script. Replace the urls and your email address with the correct values. NOTE that running this script you agree Let's Encrypt's conditions.
> 
> For Centos 7 type:
> 
> bash setup/install-centos7-local.sh

Where can I adjust the parameters for example xhanging hostname and mysql remote database as we normally do it in v2 by editing the config/production.toml?

**Comment by bures** [comment]
There is no config/production.toml in v2. You are mistaking the old Mailtrain v1 (in master) with the new Mailtrain v2 beta (in development branch). If you are not sure how things work, just use the install script on fresh CentOS minimal instance. 

If you need you existing data, you can try to make database dump and transfer the files to the new Mailtrain v2 instance. First install it, then copy the DB and only then run Mailtrain. However, unless you have something valuable there, I would not do it. The database migration does not work 100% because there are just too many corner cases to be covered. Mailtrain v2 is a completely new product.

**Comment by kusaasira** [comment]
Am aware of how it works. Only question is I wanted to configure my mysql to be on a remote host and this server where am installing the v2 Beta runs on nginx.
