### ISSUE TITLE
What is the cid field in the subscription schema?

### ISSUE THREAD

**Issue by brickcap** [Mailtrain-org/mailtrain#230]
Hi,

I'm planning to write a trigger on mysql so that every registered user on our table is automatically added to the subscription table in the mailtrain database. The subscription schema contains a [cid filed](https://github.com/Mailtrain-org/mailtrain/blob/master/setup/sql/mailtrain.sql#L261) with a not null constraint. 

Could you let me know what the cid field is used for and how is it generated in the mailtrain application? Since it is varchar can I simply generate a uuid and store it in the cid field? 

I took a look at the [fakedata](https://github.com/Mailtrain-org/mailtrain/blob/master/setup/fakedata.js#L13) file and some of the fields like company and phone number are not present in the schema. How are these mapped? 

Thanks,
Akshat

**Comment by andris9** [comment]
`cid` is generated with the `shortid` module, see [this line](https://github.com/Mailtrain-org/mailtrain/blob/master/lib/models/subscriptions.js#L92). Phone number and such are custom fields, these are not present in the initial schema, the schema is updated when custom fields are added. Instead of using MySQL directly I'd suggest to update subscriptions via the HTTP API.
