### ISSUE TITLE
Numerical Merge Tags with value 0 don't display.

### ISSUE THREAD

**Issue by markalston** [Mailtrain-org/mailtrain#236]
If you use a custom field with value set to 0 it will not display properly.  

The issue seems to be in lib/models/subscriptions.js

I have a fix which I am certain can be done more elegantly.  I simply added a check to see if the merge value is 0 and then to just use that.

It seems to have solved my issue.

```
module.exports.getWithMergeTags = (listId, cid, callback) => {
    module.exports.get(listId, cid, (err, subscription) => {
        if (err) {
            return callback(err);
        }

        if (!subscription) {
            return callback(null, false);
        }

        fields.list(listId, (err, fieldList) => {
            if (err || !fieldList) {
                return fieldList = [];
            }

            subscription.mergeTags = {
                EMAIL: subscription.email,
                FIRST_NAME: subscription.firstName,
                LAST_NAME: subscription.lastName,
                FULL_NAME: [].concat(subscription.firstName || []).concat(subscription.lastName || []).join(' '),
                TIMEZONE: subscription.tz || ''
            };

            fields.getRow(fieldList, subscription, true, true).forEach(field => {
                if (field.mergeTag) {
                    if (field.mergeValue === 0 ) {
                        subscription.mergeTags[field.mergeTag] = field.mergeValue;
                    } else {
                        subscription.mergeTags[field.mergeTag] = field.mergeValue || '';
                    }
                }
                if (field.options) {
                    field.options.forEach(subField => {
                        if (subField.mergeTag) {
                            subscription.mergeTags[subField.mergeTag] = subField.mergeValue || '';
                        }
                    });
                }
            });
            return callback(null, subscription);
        });
    });
};
```

**Comment by markalston** [comment]
Spoke too soon. It looks like the same changes need to be made in services/sender.js for the actual sent emails to work with values of "0".

```
...
            fields.getRow(fieldList, subscription, true, true).forEach(field => {
                if (field.mergeTag) {
                    if (field.mergeValue === 0 ) {
                        subscription.mergeTags[field.mergeTag] = field.mergeValue;
                    } else {
                        subscription.mergeTags[field.mergeTag] = field.mergeValue || '';
                    }
                }
...
```

**Comment by witzig** [comment]
Numerical Merge Tags with value `0` now display properly, but there's another issue. 

If the subscriber sets the value to `0`, yet the fields default display value is e.g. `3`, the merge tag displays `3` as we can't differ whether the `0` in the DB is was an 'empty' value or not.

To get around this we'd need to store `NULL` instead of `0` for empty values. This, however, would break current behaviour for list segmentation (based on number fields), making new subscribers with `NULL` values unreachable.

I think the better solution would be to init the field with its `default value` (which is currently only used for display, not segmentation) or `0` if no default value is set. This should only affect existing list segments minimally, as it seems unlikely that someone relies on their default value for display but not segmentation, and thus most default display values are likely set to `0`, if at all.

@andris9, @bures, what do you think? Thanks.
