### ISSUE TITLE
Custom Fields Using Date for automated triggers

### ISSUE THREAD

**Issue by Roost** [Mailtrain-org/mailtrain#273]
Due to the formatting support for dates(`DD/MM/YYYY`), all custom fields based on dates are stored at midnight (`00:00:00`).  This means any automation trigger schedule via the API after 6am to run at `0 days after` the supplied date, will be missed. (See comment - trigger.js Line 101 - `6 hour window after trigger target to detect it`).

Is there any solution to this, or a suggestion how this could be fixed?

**Comment by witzig** [comment]
Good catch, thanks.

I don't know why [the treshold](https://github.com/Mailtrain-org/mailtrain/blob/master/lib/models/triggers.js#L101) has been set to 6h in particular, maybe @andris9 could shed some light on this, but I think it could be easily fixed by setting it to 24h. Do you spot any downside or side effect if we'd bump the treshold to 24h?

**Comment by Roost** [comment]
From my testing, it seems the 24 hour change will work as expected, and I can't think of any negative side effect. Should I submit a PR for that change?

**Comment by witzig** [comment]
Thanks!
