### ISSUE TITLE
Problem with HTML editor (Summernote)

### ISSUE THREAD

**Issue by ubergeekady** [Mailtrain-org/mailtrain#276]
There seems to be multiple problems with the HTML editor. I reported one earlier too.

1. When i enter a link in the HTML like -
http://trackingdomain.com/aff_c?offer_id=332&aff_id=4704

The link somehow gets changed to this after i save it -

http://trackingdomain.com/aff_c?offer_id=332&amp;aff_id=4704

This link cannot work.

2. HTML edits won't get saved if you click on "Update" button directly (without switching back from code view). If you switch back from code view and then click Update, it gets saved.

**Comment by witzig** [comment]
The encoding of `&` is the expected behaviour as HTML entities inside HTML attributes are parsed by the browser.

> This link cannot work.

If you copy such a URL and paste it into the address bar of your browser, it won't work. But if you click the link in the preview mode of Summernote, or in the emails you send, the link will work as expected.
