### ISSUE TITLE
how to configure it to run mailtrain with 4 ips?

### ISSUE THREAD

**Issue by ajmalkhanjamro** [Mailtrain-org/mailtrain#283]
@andris9 
hello i am try to configure mail train to rotate emails via multiple ips linked to my server i am running linux ubuntu 14.04 how can i proceed configured every stuff but stuck here never tried want to rotate sending process to each ip equaly so ips dose not demage for sending large campaigns

**Comment by witzig** [comment]
I'm afraid, Mailtrain itself can't be configured to use multiple IPs for sending messages.

**Comment by ajmalkhanjamro** [comment]
bro i used the bundled version of mailtrain it comes with zone-mta  its mailtrain probelm

**Comment by andris9** [comment]
@ajmalkhanjamro in order to use IP rotation with Zone-MTA you must have set your network interfaces properly up. This is how you can check if it works or not:

Let's say your "default" IP address is 137.74.46.110. If you call curl against some IP address resolving service like ipify then you should get the same IP in return

```
$ curl 'https://api.ipify.org?format=json'
> {"ip":"137.74.46.110"}
```

In addition you might have set up in the same machine a network interface for 178.33.49.66. This means you should see that address somewhere in the output of `ifconfig` command.

```
$ ifconfig
...
> inet addr:178.33.49.66
```

and you should be able to use this address with curl as well. This time the IP response should match the IP of the interface

```
$ curl --interface "178.33.49.66" 'https://api.ipify.org?format=json'
> {"ip":"178.33.49.66"}
```

How to configure your server with multiple IP network interfaces is way out of scope for both Mailtrain and Zone-MTA. This depends from hosting provider (how the IP is routed to your server) and also from the distro you are using. You should ask help from your hosting provider to set this all up.

**Comment by ajmalkhanjamro** [comment]
@andris9  thanks bro after long time got clear answer let me checkout my ubuntu machin and see netowrk interfaces  if they are static  and how many ips are assigned to it will contact hosting also  and if any problem still exit will post here
