### ISSUE TITLE
User Management (Multiple Users)

### ISSUE THREAD

**Issue by mattmoesen** [Mailtrain-org/mailtrain#306]
hello,

i wanted to know if it is possible to add another user (to login to mailtrain) because currently there is only the user "admin".
i found some issues concerning users permissions, so i think it should be possible. but the only mentioned way adding another user was directly in the db. is this correct or is there a better solution?

many thanks!

br,
matthias

**Comment by bures** [comment]
Dear Matthias. 

You can create a new user by inserting an entry to users table in DB. Note however have admin permissions. There is currently no way to restrict the access.

Proper user management is on the way. But it will take a few more months because it is connected with the bigger rehaul on user-interface, etc. (see #223, #253).

**Comment by mattmoesen** [comment]
ok many thanks

**Comment by Itsmesri** [comment]
Is this feature not done yet? Looking for user management.

**Comment by dazrave** [comment]
Another +1 vote on this feature. So fair loving mailtrain but would also love to split out the admins who are using it.

**Comment by sgrayban** [comment]
3 years and still not implemented... please add!

**Comment by bures** [comment]
Check Mailtrain v2
