### ISSUE TITLE
ER_NO_SUCH_TABLE: Table 'mailtrain.subscription__1' doesn't exist

### ISSUE THREAD

**Issue by ghost** [Mailtrain-org/mailtrain#378]
I ran campaign after importing 2000 user in CSV file and I could not send mail with the following error.
This error continues to be output every 5 seconds.

There is no subscription__1 table in mysql indeed. There is a subscription__2 table that exists.

Do you know the cause?

ERR! Mail Error: ER_NO_SUCH_TABLE: Table 'mailtrain.subscription__1' doesn't exist
ERR! Mail     at Query.Sequence._packetToError (/root/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
ERR! Mail     at Query.ErrorPacket (/root/mailtrain/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
ERR! Mail     at Protocol._parsePacket (/root/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:279:23)
ERR! Mail     at Parser.write (/root/mailtrain/node_modules/mysql/lib/protocol/Parser.js:76:12)
ERR! Mail     at Protocol.write (/root/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:39:16)
ERR! Mail     at Socket.<anonymous> (/root/mailtrain/node_modules/mysql/lib/Connection.js:103:28)
ERR! Mail     at Socket.emit (events.js:160:13)
ERR! Mail     at addChunk (_stream_readable.js:269:12)
ERR! Mail     at readableAddChunk (_stream_readable.js:256:11)
ERR! Mail     at Socket.Readable.push (_stream_readable.js:213:10)
ERR! Mail     --------------------
ERR! Mail     at Protocol._enqueue (/root/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:145:48)
ERR! Mail     at PoolConnection.query (/root/mailtrain/node_modules/mysql/lib/Connection.js:208:25)
ERR! Mail     at db.getConnection (/root/mailtrain/services/sender.js:202:44)
ERR! Mail     at Ping.onOperationComplete [as _callback] (/root/mailtrain/node_modules/mysql/lib/Pool.js:110:5)
ERR! Mail     at Ping.Sequence.end (/root/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
ERR! Mail     at Ping.Sequence.OkPacket (/root/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:97:8)
ERR! Mail     at Protocol._parsePacket (/root/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:279:23)
ERR! Mail     at Parser.write (/root/mailtrain/node_modules/mysql/lib/protocol/Parser.js:76:12)
ERR! Mail     at Protocol.write (/root/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:39:16)
ERR! Mail     at Socket.<anonymous> (/root/mailtrain/node_modules/mysql/lib/Connection.js:103:28)

**Comment by bures** [comment]
Not really sure what happened. Do you have some particular minimal steps to reproduce this error?

**Comment by rikmendes** [comment]
Not sure what happened neither but we have the exact same problem, if anything was deleted it can be anything, a draft campaign, a list, a subscriber etc...

here's our log file : https://paste.digityser.org/icewohorep.makefile

I already restored my mailtrain app from 7h ago and the problem is included, I don't know how long I have to go back to find a database that isn't suffering this problem. 

Until this error is solved, there is no way to send any email campaign after the test we did. 

Any idea how to compose a mysql command to remove the "missing table" ?
and from where should this table removed if the table is already "non existing" ?

**Comment by Hocuri** [comment]
We just had the same issue, also found no solution.

Possible steps to reproduce:
- Create a new list
- Create a new RSS campaign that sends to this list
- Delete the list

Possible technical explanation (without knowing anything about the code):
- The RSS campaign tries to send a new email to the list.
- However, the list is deleted, so sending fails.
- This *** the sending queue because MT always tries to send this email before sending other emails, but it fails and then the other emails are not sent, either.

OTOH, @rmdes said that it also happens if a draft campaign is deleted - if this is true, then my theory is either incomplete or wrong.

**Comment by bures** [comment]
My guess this is a new issue. The previous issue from 2018 seems to be related to MailTrain v1. You are likely referring to V2. Isn't it?

**Comment by Hocuri** [comment]
Where do I find the version? Also, we just found a solution (not me, but someone else), hang on...

**Comment by Hocuri** [comment]
Actually, I think we are using v1, because

```
$ cat README.md 
## Mailtrain v2 beta is available. [...]
```

The solution was:

`select id from campaigns where list = 1;` (or whatever the deleted list id causing problems is)

Then delete everything that's returned
