### ISSUE TITLE
Allow global custom forms

### ISSUE THREAD

**Issue by kolaente** [Mailtrain-org/mailtrain#380]
It would be great if we could have global custom forms. We have multiple lists with different people in our org, they all should have the same form/settingspages/etc. I ended up copying the templates from one list to the other one.

More context: As we're a french association, our newsletter members are 99.9% french, so they should have all the forms and confirm mails in french. I translated these and copied them afterwards, but this would be way easier if one could just create one global form to use for every list.

**Comment by kolaente** [comment]
Another thought I just had (which is probably out of scope of the original issue): If we'd save the language of a subscriber, we could show him the settings/page/subscribeform/everything else in his language. If we'd go with that, I'd be happy to share my translated templates.

**Comment by bures** [comment]
@kolaente Your idea about shared forms makes a lot of sense. Actually, it's already implemented as part of the big update I'm working on (see the picture below). 

The problem is that it's connected to rather big changes on the server and client (https://github.com/bures/mailtrain/tree/access) that I have not yet completed. My estimation is that I could have a beta by summer. 

![capture](https://user-images.githubusercontent.com/1729239/35922583-3b9a98dc-0c1e-11e8-9242-013446e6935d.PNG)


As for the language per subscriber. This is certainly a good idea. The problem is that the way this is currently implemented assumes one global language per installation. For custom form, it would mean selection of custom form set by the language. This is something I won't be able to include in the big update I wrote about above. Maybe later...
