### ISSUE TITLE
Language switcher in the UI

### ISSUE THREAD

**Issue by kolaente** [Mailtrain-org/mailtrain#381]
As Mailtrain is capable of speaking multiple languages, it would be great if we could have a language switcher in the web UI to switch languages when browsing the web interface.

**Comment by bures** [comment]
I'm afraid it is not possible now because Mailtrain is bound to one language per server instance. However, the new version (in branch development) manages the languages on the client side, so a language switcher (per client) should be possible. However note that it won't work for  subscription forms, which are rendered on server.

**Comment by hadifarnoud** [comment]
I think subscription form language is more important than the actual admin UI. I can get use to English UI but for the forms, it has to be in my own language
