### ISSUE TITLE
Conditional Merge Tags

### ISSUE THREAD

**Issue by chris-aeviator** [Mailtrain-org/mailtrain#39]
It would be benefitial if mailtrain would be able to handle conditional merge tags for sending e.g. different salutations based on the gender of the subscriber.

Mailchimp solves this by letting the user write "pseudocode" conditionals like:

_|IF:SALUTATION=Mr |_
Sehr geehrter _|SALUTATION|_ _|LNAME|_,
_|ELSEIF:SALUTATION=Mrs |_
Sehr geehrte _|SALUTATION|_ _|LNAME|_,
_|ELSE:|_
Sehr geehrte Damen und Herren,
_|END:IF|_

**Comment by chris-aeviator** [comment]
@andris9 

I'd be willing to contribute working on this, if you could provide some intro how this could be achieved in a fast manner (not planing to bring you more refactoring trouble =) )

**Comment by andris9** [comment]
I haven't done this so far because conditional tags are quite a complicated problem. Replacing individual tags is easier (current merge tag replacement happens [here](https://github.com/andris9/mailtrain/blob/master/lib/tools.js#L178-L182)) because you can make full replacements – you take a merge tag name and replace it with actual value. Conditional tags on the other hand depend on the surrounding HTML context and blindly removing unneeded code might end up with a broken HTML.

Consider this example. let's say I type in the conditionals using the WYSWYG editor and end up with the following (valid) code:

```html
<div>
  <div style="some-wysiwyg-editor-inserted-rule">
    |IF:SALUTATION=Mr |
      Sehr geehrter |SALUTATION| |LNAME|,
  </div>
  |ELSE:|
    Sehr geehrte Damen und Herren,
  |END:IF|
</div>
```

If I replace merge tags in this code and salutation is not MR then I end up with this HTML:

```html
<div>
  <div style="some-wysiwyg-editor-inserted-rule">
    Sehr geehrte Damen und Herren,
</div>
```

As you can see there is a `</div>` missing from the output. For simpler designs it probably does not matter much but for anything more complex it can easily mess everything up.

**Comment by shwaydogg** [comment]
What about not all logic but just an option if the field is blank...  would that be simpler? It's a very common use case I believe.

**Comment by sokulski** [comment]
> What about not all logic but just an option if the field is blank...

The ability to add a fallback if a field is empty already exists:

> Merge tags are tags that are replaced before sending out the message. The format of the merge tag is the following: [TAG_NAME] or [TAG_NAME/fallback] where fallback is an optional text value used when TAG_NAME is empty.
