### ISSUE TITLE
RGPD/GDPR compliance 

### ISSUE THREAD

**Issue by arthurlogilab** [Mailtrain-org/mailtrain#420]
Is mailtrain RGPD/GDPR compliant, and if not are there any plans to make it so ? 

(sorry for the lack of technical content, am quite new to this regulation)

**Comment by bures** [comment]
I'm no expert for GDPR. But as far as I understand it there are two principal issues that need to be taken care of:

1. Subscribers should give their explicit consent to be included in a list.
2. Subscribers should be able to get forgotten.

ad 1) We can assume that if someone subscribes using the subscription form, this equals to explicit consent. The problem may be with importing a list. Here it is the responsibility of the person importing the list to get explicit consent from all the people on the list.

ad 2) This is Mailtrain's responsibility. The only problem I see is that Mailtrain handles unsubscriptions by marking the person as "unsubscribe". It does not delete the entry though. I believe we would need to patch Mailtrain such that it really deletes the person from a list when the person unsubscribes. Note however, that this will mean that we one looses track of persons that cancelled their subscriptions.

It should be relatively easy to implement it. I would suggest that we have a parameter in Mailtrain's config that controls how unsubscription is done (whether just marking a person as unsubscribed or deleting the person). Then we would have to implement the automatic deletion. 


So coming back to your question - I'm afraid that Mailtrain by itself is currently not compliant, unless you want to regularly check and delete manually those people who unsubscribed. But the change would be easy. Not sure though if there is anyone willing to take it up now.

**Comment by rrooij** [comment]
Instead of deleting a record, you can also anonymize the record, by erasing all contact fields (email, first name and custom fields) but keep tracking that there *was* someone who subscribed.

Otherwise it will be impossible to show nice statistics about whole lists (how many unsubscribed in total) etc.

**Comment by bures** [comment]
Yes. That's also a viable option.

**Comment by killua-eu** [comment]
That might actually be the right option, because even if the person unsubscribes, the person may ask per GDPR how was their personal data used, may they not? If I'm not mistaken, adding a database column and hash the e-mail addresses might be the best way to go.

**Comment by markuskreusch** [comment]
We currently use mailtrain and our way to go, if this is not changed in the system, would be to delete unsubscribed entries on a regular basis.

I do not believe that after deletion the right to ask how the data was processed still holds. If it would be, true deletion of data would never be possible.

From my understanding hashing the mailadress will not be enough because mailadresses often follow a simple pattern or maybe publicly known. Thus hashed mail adresses would still allow somebody to extract most or at least some of the cleartext adresses (by using rainbow tables or bruteforcing). There are countermeasures against this like using a long salt and long running hash function etc. but even then someone with a list of mailadresses could still extract information from the system by determining for each mailadress if and when it was subscribed / unsubscribed. After unsubscribing such information must be deleted. Erasing all contact fields should be the way to go. 

In fact a lawyer should be consulted to get a definite answer. Personally I would be happy to see contact data ereased on unsubscribe.

**Comment by bures** [comment]
I did a small research. From what I was able to gather, GDPR requires you to be able to give an overview what data of a particular user are currently kept. In this respect, if someone unsubscribes and we delete him/her, no data are kept any more. Thus if this person asks, we tell him/her that no data are kept. 

As such, I think the solution of @markuskreusch should be right. I think we can also call this a recommended practice until someone implements the automatic deletion upon unsubscribe.

**Comment by anselmh** [comment]
> That might actually be the right option, because even if the person unsubscribes, the person may ask per GDPR how was their personal data used, may they not? If I'm not mistaken, adding a database column and hash the e-mail addresses might be the best way to go.

For completeness: Hashing data still counts as storing personal data, it just lowers the requirements of how you need to protect this data. However, you’re not allowed to store any data (incl hashed) when a user asks to delete data.

One more thing that no one has considered here yet in regards to compliance is that you need to prove the consent which means you need to have the opt-in/subsribing date. This seems to be already recorded in the database but is vaguely shown as "23 days ago", maybe a tooltip/title field should reveal the complete datetime additionally?

**Comment by mircsicz** [comment]
Just found this thread as a client pushed me to find a solution for his GDPR issue...

I'ld love to see a config option that would lead to an automatic deletion of unsubscribe's

But how would you handle the following topic:
let's say I've imported a list of contact's by CSV and I'ld like all of them to approve their membership by clicking the subscribe button once again. And everyone who didn't click till the 25th of may get's unsubscribe'd silently... Could this be done in a simple way?

**Comment by calbasi** [comment]
What Mailchimp do is create a new "consent / GDPR field", and send a mail to all your subscribers asking them to review/edit a form, where this field is shown (among others, if you want, like personal contact data).
Then, you have will be able to segment your mailings just sending them to "GDPR compliance" segment, and not sending more mailing the others...

**Comment by sven-weber** [comment]
I faced the issue of how to regularly delete the unsubscribed users myself and a solution, instead of doing this by hand, might be to add a event in the mysql database. 

The following SQL Script would deleted all unsubcribed users on a daily basis. 

```
CREATE EVENT 
ON SCHEDULE EVERY 1 DAY
STARTS '2014-01-18 00:00:00'
DO
DELETE FROM `subscription__1` WHERE status = 2
```

In oder to use it, events need to be enabled 
```
SET GLOBAL event_scheduler = ON;
```

**Comment by forgeOneHQ** [comment]
Should be already implemented in v2. Please try the latest v2 version :)
