### ISSUE TITLE
GraphQL API

### ISSUE THREAD

**Issue by ghost** [Mailtrain-org/mailtrain#459]
Are there any plans to add graphql api on top of mailtrain?

I've been using mailtrain and I love it. The built in REST API is a good start but it doesn't cover the library completely. So I have decided to implement a graphql api using apollo-server.

I opened this issue to let everyone know that the work is in progress. I'll submit a pull request in a couple of days.

Meanwhile, if you have any pointers, please share.

**Comment by bures** [comment]
Good. Keep us posted. It would be good if you could explain your use case and what API functions are needed. I'll be refactoring the API for Mailtrain v2, so it's good if I understand what the API is used for. Thanks.

**Comment by dhruvin2910** [comment]
I had a long journey developing that API. Most important design decision was not to modify the core API at all (so that it can be just an addon to mailtrain). I developed (and rejected) 3 versions of it. This is why my couple of days were not **just** a couple of days. Right now working on the final version.

REST clone
1. Mirrored existing library (just exposed everything from lib with JSON types)
    * Which has been working great. But it's not the ideal way to implement it.
    * No joins
2. Implemented it with appropriate types using apollo
    * Since the core library is not developed with GraphQL in mind, not all returned objects follow a standard. So there are a lot of data types (a lot of them).
    * Slow joins

Queries done in versions above were never optimal (painfully slow sometimes) because we have joins there (1 + N issue).

The GraphQL way
1. Instead of using lib for queries I decided to use db directly (for mutation I still use lib).
    * Which solved the types problem.
    * Manual pagination (since I'm not using lib anymore)
2. Join Monster with Relay compliance for the win

Now the latest API exposes everything that mailtrain touches in read only manner using queries. And lib is exposed using mutations making it exhaustive and optimised.

**Comment by dhruvin2910** [comment]
Use cases:
1. Segmentation using algorithms (dynamic, every time a campaign is to be sent)
2. Client specific dashboards and applications
3. Custom template creator
4. Custom template components
5. Setting custom field values (generated from various sources, not just from Custom Forms)
6. Custom email scheduler (based on custom field values)

Some of the use cases are covered by the web app (which is great). But programmatic access to them would be great for automation.

**Comment by bures** [comment]
Nice. Let me know once you have the code somewhere. My intention is to create a brand new API for Mailtrain v2.  To retain some level of compatibility, the API version (v1 or v2) would be selectable via an HTTP header (or similar). So any good examples of what the v2 API should look like are more than welcome. My impression is that the v1 API is not very systematic. It's more like a collection of specific functionalities that someone needed at some point.

**Comment by renewooller** [comment]
any progress on this one?

**Comment by dhruvin2910** [comment]
The project we were working on, did not take off. I stopped working on the GraphQL part. It seems to me that MailTrain has changed quite a lot since then. No updates from my side 😐.
