### ISSUE TITLE
Mailtrain v2 - What are your requirements for GDPR compliance?

### ISSUE THREAD

**Issue by bures** [Mailtrain-org/mailtrain#491]
I'm now started implementing some basic GDPR support. At this point, I foresee the following features:
- When a subscriber unsubscribes, his/her data are deleted from the subscription table, only an entry with hashed email remains. This helps prevent resubscription upon import.
- After defined time (e.g. 60 days), even the hashed emails are deleted.
- Both the options above can be enabled/disabled in config
- Additional custom form "Privacy Policy"

Anything else?

**Comment by jfqd** [comment]
All requests to other services like fonts.googleapis.com, premailer.dialect.ca, etc. should be removed.

**Comment by jonathanmmm** [comment]
> All requests to other services like fonts.googleapis.com, premailer.dialect.ca, etc. should be removed.

Seems to be that premailer.dialect.ca is not used anymore (https://github.com/Mailtrain-org/mailtrain/pull/950)
with this https://github.com/Mailtrain-org/mailtrain/pull/1219 google fonts accessed should also be removed.

I propose a task list update, I would start at what I found out

**Comment by jonathanmmm** [comment]
- [ ] Remove connections to all other services (If not possible the user has to be asked in advance and only after the user explicitly accepts this, is extra content loaded) - seems to be done by the most part, can't find any other connections (when google fonts are also removed)
- [ ] Custom Form Privacy Policy (maybe document better how to link this, if List is private) - but feature is done
- [ ] Make tracking disabled by default (instead of right now enabled by default)
- [ ] Make tracking only part of IP address and make anonymous tracking (create id for every user that is deleted from database upon opening, but id is after creation not tied to user, so even with access to database no user can be identified that way)

Next three things are done, right?
- [ ] When a subscriber unsubscribes, his/her data are deleted from the subscription table, only an entry with hashed email remains. This helps prevent resubscription upon import.
- [ ] After defined time (e.g. 60 days), even the hashed emails are deleted.
- [ ] Both the options above can be enabled/disabled in config

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
