### ISSUE TITLE
[[ QUESTION ]] can i modify sender information per list?

### ISSUE THREAD

**Issue by babatundebusari** [Mailtrain-org/mailtrain#514]
I have multiple lists that represent different websites

can i change the sender information to individual list?

**Comment by bures** [comment]
What do you mean by "sender" information?

**Comment by babatundebusari** [comment]
under `settings` >> `campaign defaults`

**Comment by bures** [comment]
You can do so in Mailtrain v2 (beta). There you can define a number of "send configurations". When you create a list, you assign it one send configuration. The send configuration defines how to send out emails and the default email headers.

**Comment by babatundebusari** [comment]
how can i get mailtrain v2 beta?
am using docker-compose

**Comment by bures** [comment]
See the instructions here (https://github.com/Mailtrain-org/mailtrain/tree/development). Specifically check the "Preparation" section on the top and the "Deployment with Docker and Docker compose" section on the bottom of the page.

**Comment by babatundebusari** [comment]
ok cool..will check it out
can i upgrade my current deployment or things will break?

also anywhere to check out all the new features added to v2?

thanks

**Comment by bures** [comment]
The migration from v1 to v2 should take care of most of the things. However there are some gotchas (see https://github.com/Mailtrain-org/mailtrain/blob/development/UPGRADE.md). You should definitely make a DB backup.

Another thing is that the migration has not been properly tested. But I'll be happy to fix the bugs that you encounter during the update.

However, I would first suggest you try a clean installation, just that you can have a look around. (Note that if you are using your self-hosted ZoneMTA, it won't be needed any more since Mailtrain v2 comes with an embedded ZoneMTA.)

**Comment by babatundebusari** [comment]
well i dont have a production setup yet...so will save myself the headache and just deploy brand new separately

by the way how can people contribute financially to this project?
i don't see how you guys are able to keep this project going to be a really great project

will love to see more activity on this project and willing to support as well
please lets get this project to be much more active because there is nothing else that comes close opensource wise

**Comment by bures** [comment]
Thanks for the offer. I'm afraid that I'm in a situation now where money contribution won't unfortunately speed up things. Making a day have 48 hours would. :-)

**Comment by babatundebusari** [comment]
yeah got it to work
anyways will close this issue now
and figure out the features on the beta

**Comment by mgnisia** [comment]
Hey @babatundebusari would it be possible that you could share a minimal working example to show your mailtrain-config? That would be really nice! 👍

**Comment by mgnisia** [comment]
solved it 👍
