### ISSUE TITLE
Feature request - Namespace filtering

### ISSUE THREAD

**Issue by priethor** [Mailtrain-org/mailtrain#543]
Now that v2 supports namespaces and the application can be "partitioned" allowing multitenancy, it would be really cool to be able to filter by an "active namespace" provided the user has access to more than one.

For example, in our Mailtrain instance we have campaign managers having access to the root namespace or a set of namespaces, but our typical use case involves "concentrating" on a namespace and jumping between the content available only in that namespace, as in:
1. Manage list(s) assigned to namespace A
2. Manage templates and/or campaigns assigned to namespace A
3. Go back to 1 if required
4. Manage list(s) assigned to namespace B
5. Manage templates and/or campaigns assigned to namespace A
6. Go back to 4 if required
7. Etc.

It would be very helpful to have a dropdown in the top bar to select the "active namespace", so that all content is filtered by that namespace as if the user didn't have access to other namespaces.

**Comment by bures** [comment]
I agree. Good point. I had something similar in mind too. I guess, we can agree on having some dropdown with namespaces in the top bar. 

Would it be useful to have also a checkbox "Include sub-namespaces"? Or is it something you don't need in your use-case? I'm asking because implementing the children will be some complication, which is however worth it, if this is a needed use-case.

Thanks.

**Comment by priethor** [comment]
Honestly I hadn't even considered it, as I was assuming it would work in the same way as the user roles do, which they do include the children. For example, if a user has Campaign Admin role in the root namespace, he sees everything belonging to its subtree, so I guess this dropdown should be consistent with that behaviour.

In my use case, we are just starting with v2 and still arranging our content hierarchically according to the namespaces, so I really can't tell whether single node or subtree is better, but with just a few days in v2 after a year with v1, I'm only certain that it needs to be consistent with the roles or it can become messy and difficult to understand.

**Comment by bures** [comment]
I see. A bit of the issue is that roles can be configured whether to include the sub-namespace content or not. It's more like a coincidence that Campaign admin is configured to include sub-namespaces. You can see it in https://github.com/Mailtrain-org/mailtrain/blob/0c3510d62695e05b58f83da447d6b9564ab12300/server/config/default.yaml#L259

The `children` section determines what permissions there to entities in children namespaces. You can thus theoretically have larger permissions to the namespace than you have to the children. Though I had no use case for this so far.

What we could do also is to have a global permission that would determine whether one sees the children or not.  That would be configured in https://github.com/Mailtrain-org/mailtrain/blob/0c3510d62695e05b58f83da447d6b9564ab12300/server/config/default.yaml#L236
This way, one could say how exactly a specific user role should work - i.e. whether to display children or not. This way, it would be consistent per user-role (and consequently per user).
