### ISSUE TITLE
Prometheus metrics endpoint

### ISSUE THREAD

**Issue by morremeyer** [Mailtrain-org/mailtrain#557]
Hey everyone,

I searched through the doc and wiki as well as the issues, but couldn’t find anything so far.

Is there a plan to provide a prometheus metrics endpoint sometime? I’d very much like this feature to trend campaigns and the opening/clicked stats etc.

If there is nothing planned yet but you (= the maintainer[s]) are interested in that feature, I’ll have a look at implementing it myself - haven’t done too much JS lately, so I’d be glad for some hints in that case.

**Comment by bures** [comment]
No plans for Premetheus. However, it is an interesting option. I was planning to do something similar for IVIS (https://github.com/smartarch/ivis-core), which is a similar project we are developing at out university. Nevertheless, no problem to have support for both.

In any case, I would suggest that you develop it for Mailtrain v2 (beta). I'm focusing all development there, as this is supposed to replace Mailtrain v1 soon. 

I already created a class that should provide an abstraction gathering those different events that occur in the system (https://github.com/Mailtrain-org/mailtrain/blob/development/server/lib/activity-log.js). It's not complete, but already contains some examples. The idea is that in this class, we would further send the events to IVIS, Prometheus, etc., as configured in the config.

So if you are willing to help, please have a look there and continue in instrumenting the different places in code so that events are gathered there and sent to the activity-log. Then another point will be to route the activity log to Prometheus. This however will have to be done in some systematic way, so that we can route it to IVIS the same way, etc.

I'll be happy to help. Just let me know. Thanks.

**Comment by Avalarion** [comment]
@mauricemeyer this could be interesting for us, too. I am not really able to help you out with JS but I am able to test if required or do some structuring.

**Comment by forgeOneHQ** [comment]
@morremeyer you are welcome to participate on developing this and create a pull request since it is an open source project! :)
