### ISSUE TITLE
zonemta killed !

### ISSUE THREAD

**Issue by shahzaibcb** [Mailtrain-org/mailtrain#586]
Hi,

We have  a list of 12000 emails that is being sent out with 30 mails per hour threshold set. During the process we noticed that out of 6000 delivered emails 4000 are bounced back. That was a shocking for us that how come bounce back ratio could be that high. On checking the server we found that zone-mta was crashed and due to which there were connnection refused errors being logged against 2525 port. Following is the logs against zonemta crash : 

`https://pastebin.com/JP6azUGB`

Do you have any clue behind the crashing of zonemta ? Mailtrain other processes were running but only zonemta was killed. Also the most important part, can we re-send emails to 4000 users whose mails got bounced back just because zonemta was down ?

**Comment by bures** [comment]
That looks like zone-mta problem. @andris9, please, any idea about this? My apologies if I messed up anything.

@shahzaibcb - can you tell us which version of zone-mta are you using? Just do `npm ls zone-mta` in directory `/opt/mailtrain/zone-mta` (or update based on the location of your mailtrain installation).

In any case, I should incorporate to mailtrain support for restarting zone-mta after it fails.

As for those 4000 users. Is it that the users bounced back (i.e. are marked as bounced in mailtrain list)? Or do they appear as subscribed in the list?

If they appear as subscribed, it's likely that zone-mta has them still in its mongodb and will deliver them once it is again started by mailtrain (once you restart mailtrain).

If the users are marked as bounced, then you need to fix it in mysql. Update the column status from 3 -> 1. Also check the blacklist table and delete the entries if the email addresses got blacklisted due to bounce. Once you do this, you can go back to the campaign. Those 4000 users should appear there as users to whom the campaign has not been sent yet. Then just click "Send" to send the campaign to the rest of the users.

Generally, I would recommend trying it on a smaller sets of users first and then extend it to the rest.

**Comment by forgeOneHQ** [comment]
@shahzaibcb please try again with the latest v2 version and create a new issue if this issue still comes up.
