### ISSUE TITLE
E-mails are redirecting to promotions tab not in primary tab in gmail.

### ISSUE THREAD

**Issue by pranjal2892** [Mailtrain-org/mailtrain#594]
Hey,
is there any way to change the settings in mailtrain to send emails as primary emails in inbox.
By default, my emails are being received in promotions in Gmail, not in primary mails.
And it's my pre-requisite to receive mail in the inbox.
Kindly help!!
thank you

**Comment by bures** [comment]
I guess this is connected with the headers included to the emails (such as unsubscribe link). Since your emails should have an unsubscribe link (otherwise you would be violating rules at least in EU), I guess you cannot easily avoid it. If your emails are essentially marketing, then they belong to "promotions" folder in GMail.

**Comment by Epizefiri** [comment]
@bures  What if my emails are not marketing? My team was trying to use mailtrain to send "event based" emails, they are simple text mail and we would like to send it to the primary tab.

**Comment by bures** [comment]
You could play a bit with the headers that are added to the emails and see how gmail reacts. But I guess there is no simple answer to this. If you send an email to a large group of people, gmail will be theoretically able to recognize it.

**Comment by Epizefiri** [comment]
What I noticed is that in the headers of the mail there are tags like "List-Unsubscribe" or "List-ID".
Is there a way to edit those headers? should I edit the source of mailtrain?

**Comment by bures** [comment]
Try to leave it out from Mailtrain's code to see if it helps.
