### ISSUE TITLE
V2 Can't use/see block in GrapeJS mjml 

### ISSUE THREAD

**Issue by ZephOne** [Mailtrain-org/mailtrain#628]
Context:
Docker install

When using grapeJS  mjml, I cant see/use block in the side toolbar of the editor. Yet this features seems to be working inside grapeJS mjml [demo](https://grapesjs.com/demo-mjml.html)
Here is what I have:

![mailtrain_mjml_bug](https://user-images.githubusercontent.com/25317904/60530778-7544b800-9cf1-11e9-827c-4d5486d440a8.png)

**Comment by bures** [comment]
Indeed. Mailtrain just directly uses the grapesjs-mjml module. So this lies more with GrapesJS -MJML than with Mailtrain.

Honestly, the GrapesJS MJML plugin is just pure pain. It's not very maintained (still relying on MJML 3.2, etc.). I was already considering dropping GrapesJS altogether because it's just a graphical low-level editor. If someone is proficient enough to create anything complex in GrapesJS, one would be also able to just write it down in Code Editor.

Honestly, I think you too will achieve much better job (and faster) when you use the Code Editor and write the MJML there. 

If you want to build a template with a predefined set of blocks (for others who can't use MJML directly), you can try to create MJML-based Mosaico Template and then tell the end-users to use Mosaico with this template you developed. There is a full-fledged example of the MJML-based Mosaico Template. Just go to Templates -> Mosaico Templates -> Create Mosaico Template -> MJML Sample.

**Comment by ZephOne** [comment]
All right, thanks @bures

**Comment by mdehollander** [comment]
I am running into the same, editing a template with grapesjs results into a limited interface (blocks are missing). For the end users I have in mind, the GrapesJS editor fits better as Mosaico.
I see that grapejs-mjml (again) is actively maintained and has been updated to version 4 at the end of July 2019.

Would it be possible to update to a newer  version of grapesjs-mjml and fix the interface? I am running mailtrain2.
