### ISSUE TITLE
V2 Bug: users with a namespace N1 can see campaigns in namespace N1 that contain lists/SCs from N2

### ISSUE THREAD

**Issue by priethor** [Mailtrain-org/mailtrain#659]
### Steps to reproduce:

1. Create a campaign and assign it to namespace N1.
2. Assign a list or send configuration of a different, non descendant, namespace N2.
3. Log in as a user with access to N1 but not N2 and go to campaigns.
4. The user can see and edit the campaign with settings outside his scope.

### Proposed solution:

If a campaign contains data a user shouldn't have access to, the user shouldn't see the campaign.

This should be improved by not allowing to save campaigns that contain send configurations or lists outside the campaigns scope (namespace subtree), as proposed in #562 and #563.

@Charlo270398 will provide a PR shortly.

**Comment by bures** [comment]
What exactly do you mean by having a user that has access to N1 but not N2. How did you assign permissions to this user?

As for the proposed solution, I'm afraid, I have cases where I want to keep the send configuration elsewhere. The assignment of the namespaces should not by itself dictate whether you can use it in the campaign or not.

**Comment by priethor** [comment]
It would be something like:
- Root namespace
  - N1
    - N1.1
    - N1.2
   - N2
    - N2.1
    - N2.2

And we could have the following assignments:
- User: N1
- Campaign: N1
- Send Configuration: N2
- List: N2

If a user that that has access only to the N1 subtree can see and use elements out of his scope, maybe we are not understanding really what namespaces are meant for. Shouldn't them be partitions to allow/deny access to?

My suggestions in #562 and #563, base in my probably wrong misunderstanding of namespaces, include the restriction of not being able to asign Send configurations or Lists to a campaign outside of its scope. For example, a campaign in N1 shouldn't contain Send Configurations located in N2, right? We are using namespaces to work in a multitenancy setup, so each namespace is a client/project.

In order to understand your use case better, in what scenario would you want a send configuration elsewhere?

**Comment by priethor** [comment]
In any case, there are still some inconsistencies or bugs in the current implementation, such as this scenario:
- Unser in namespace N1.1
- Campaign in N1.1
- Template in N1

When the user tries to open the template, mailtrain crashes, as the user doesn't have the required permissions to load the template.

**Comment by bures** [comment]
The namespace is essentially a directory. As such, its main responsibility is to serve as a container for entities (users, campaigns, lists, send configurations, ...).

There are two options how a user may get access to an entity:
- the entity is directly shared with a user
- the entity resides in a namespace which is shared with a user

Whenever an entity is shared with a user, one has to specify what is the role of the user w.r.t. the entity. The list of these roles is configured in server config. Each entity type may define its own set of roles. A namespace is a bit special, because its roles may define also access to entities in the namespace - just look in the config.

Thus, if I share a namespace N1 with user U1 in the role `campaignsViewer`, it gives U1 permissions `[view, createTemplate, createCampaign]` to N1 and then permissions `[view, viewFiles, viewAttachments, viewTriggers]` to any campaign recursively within the namespace, etc.

Up to here, all the access settings are essentially triplets: (user, role, entity).

However, there are also so called global roles, which are essentially pairs (user, global role). This you can again find in server config. 

A user has exactly one global role. This is configured in the user edit screen. The primary responsibility of the global roles is to give the user permissions to do things which are not tied to a specific entity and have rather global effect - e.g. to manage settings.

But (and now comes probably the source of the confusion), to ease permission settings in the UI, a global role may also automatically assign shares (i.e. the triplets) to the user. For instance, an `master` global role says that `rootNamespaceRole: master`. This means that if you give a user the global role `master`, it automatically gets role `master` to the root namespace.

Similarly, `campaignsAdmin` is defined with `ownNamespaceRole: campaignsAdmin`, which means that when you assign someone a global role `campaignsAdmin`, the server automatically shares the namespace of the user with the user in the role `campaignsAdmin`. 

Thus simple scenarios may look like you described. There are however more complex scenarios, when you create a user with global role `nobody` (see the server config - `default.yaml`). This does not automatically share anything. Instead, all the shares have to be created manually. This means, I can have a namespace structure like this:

- root
  - Branch 1
    - Bulletin QQQ
    - Bulletin RRR
  - Branch 2
    - Bulletin SSS
  - Branch 3
    - Bulletin TTT

<br/>

- User U1 with global role `nobody` located in namespace A.

<br/>

- Campaign QQQ1 located in root/Branch 1/Bulletin QQQ.
- Campaign RRR1 located in root/Branch 1/Bulletin RRR.
- Campaign SSS1 located in root/Branch 2/Bulletin SSS.
- Campaign TTT1 located in root/Branch 3/Bulletin TTT.

<br/>

- Send configuration SC1 in root/Branch 1
- Send configuration SC2 in root/Branch 2
- Send configuration SC3 in root/Branch 3

There is essentially one send configuration per branch.

<br/>

Now, we assign the following shares:
- Share root/Branch 1/Bulletin QQQ with U1 in role `campaignsAdmin`
- Share root/Branch 3 with U1 in role `campaignsCreator`
- Share root/Branch 1/SC1 with U1 in role `campaignsCreator`

In this scenario, the U1 can create and send campaigns in root/Branch 1/Bulletin QQQ. For instance the user can send campaign QQQ1. The user can also create (but not send) campaigns in root/Branch 3 and below. For instance, the user can prepare campaign TTT1.

For creating the campaigns, the user can use SC1 and SC3. 

This way, you can essentially organize your assets as per you company structure and tasks (branches,  bulletins) and have user that cross-cut through the company and are responsible for certain tasks at certain levels.

**Comment by bures** [comment]
> In any case, there are still some inconsistencies or bugs in the current implementation, such as this scenario:
> 
> * Unser in namespace N1.1
> * Campaign in N1.1
> * Template in N1
> 
> When the user tries to open the template, mailtrain crashes, as the user doesn't have the required permissions to load the template.

I'll check it, but you have to tell me what roles the user has (i.e. the global role and if any direct shares).

**Comment by Charlo270398** [comment]
> > In any case, there are still some inconsistencies or bugs in the current implementation, such as this scenario:
> > 
> > * Unser in namespace N1.1
> > * Campaign in N1.1
> > * Template in N1
> > 
> > When the user tries to open the template, mailtrain crashes, as the user doesn't have the required permissions to load the template.
> 
> I'll check it, but you have to tell me what roles the user has (i.e. the global role and if any direct shares).

At this scenario the user has Campaigns Admin role and there isn't direct shares. The user can list the campaign and access to the CUD interface, but if an attribute has N1 namespace it turns to an empty field (in list and template cases), or directly it crashes (in send configuration case).

**Comment by bures** [comment]
Yep. It's a question what the correct behavior should be. The easiest is that if one does not have permissions, only an empty field is displayed. If one wants to make changes, he/she must select another namespace/send configuration.

The crash is of course wrong. It should again display only empty send configuration.

**Comment by Charlo270398** [comment]
So, I'm going to fix just the crash error.

**Comment by bures** [comment]
Yes. That would be my suggestion. Generally these cases are unavoidable in general setup. You can setup roles, namespaces and users in your system in such a way that a situation like this one cannot happen. However, it should not be hardwired in Mailtrain, because the situations where a user has multiple roles in different parts of the organisation make quite a lot of sense (at least to me).

**Comment by priethor** [comment]
Fixed the bug!
