### ISSUE TITLE
V2 bug: after renaming the field column names segments rules are broken

### ISSUE THREAD

**Issue by priethor** [Mailtrain-org/mailtrain#663]
After the migration 20190726150000_shorten_field_column_names.js in commit 8cd01fe99e466e8763e5b50555286450d6b64022, column names have been renamed, but the content of segment rules referencing those column names haven't been updated. As a consequence, many segments get broken after applying the migration.

For example:
- Old custom field name: `agenda`
- Old custom field column name: `custom_agenda_ms2iobo4vlm`
- New custom field column name after migration: `custom__ms2iobo4vlm` (with 2 underscores)
- Segment rule broken: `{"rootRule":{"type":"some","rules":[{"type":"isTrue","column":"custom_agenda_ms2iobo4vlm"}]}}`

Not sure on how to proceed, if the column renaming wasn't expected or the segment rules should be adapted in consequence. At the moment, I'm manually editing the segment rules when I need them.

**Comment by bures** [comment]
Indeed. It seems that the migration 20190726150000_shorten_field_column_names.js is just wrong. It updates only custom_fields, but not segments. The irony is that this migration is actually not needed. I just wanted to unify the style of column names. 

What I'll do for now is that I will remove the migration 20190726150000_shorten_field_column_names.js. It will come out probably in a few days as part of other updates. 

However, since you already applied the faulty migration you will have to either revert or manually fix your DB. Sorry for that.

**Comment by bures** [comment]
I pushed a fix for this. However, as I wrote before, you have to fix the DB yourself. Anyway, if you can, it would be great if you could test the fix. I made the renaming already part of the v1 -> v2 migration. Thus, if you have any v1 backup, I would be grateful, if you could test it. Thanks.

**Comment by bures** [comment]
Try the latest commit. I created a fix that will fix your segments table in the DB. You will have to run:
NODE_ENV=production node fix-20190726150000_shorten_field_column_names.js
in server/setup/knex/fixes.

**Comment by priethor** [comment]
I run the task and it fixed all broken segments, thanks!
