### ISSUE TITLE
How to resend unopened email

### ISSUE THREAD

**Issue by eenuuu** [Mailtrain-org/mailtrain#698]
Hi Everyone, 

could you help to answer the question above? basicly previous i'm using another email services to sent email blast, and now i'm trying use mailtrain. But i got problems, i didn't know how to set or resend the campaign with unopened recipient target in the campaign. 

hope you guys can help me to solve the problems.

**Comment by forgeOneHQ** [comment]
@eenuuu if they won't get open, why you would resend it again? It makes no sense since there can be few reasons why this happened. Usually you should get on sending new campaigns with reminders if they are for surveys, events etc.

Please check the latest v2 version and if you need any more help you are welcome to open a new issue.
