### ISSUE TITLE
Embedding images

### ISSUE THREAD

**Issue by StephanieHayes** [Mailtrain-org/mailtrain#717]
Hello
I cannot embed images in my Mailtrain (GrapeJS) newsletter. They don't arrive in the recipients' email. 
I've tried changing the Service url as suggested by @fwolfst but that hasn't worked either. 
I would appreciate your help to fix this.
I'm pretty desperate here as I have tried everything and my client is waiting for his company's first newsletter to be sent - it's all ready to go, but with this one important hiccup!
(I'm not an IT person by the way, so minimal tech language would be great)
Thanks very much in advance!

**Comment by fwolfst** [comment]
@StephanieHayes difficult to tell without the technical details, which one probably shouldnt share online. 
Unfortunately I cannot deliver unpaid support at the moment and feel like a responsible adult in my family at the same time.

The mail should contain links to images. Either the links are wrong or the images are not in the right place :)

**Comment by StephanieHayes** [comment]
ok @fwolfst  I understand - i'm often in the same position myself, giving out free advice and help (I'm a comms consultant). There's a point when you have to stop or you'll never earn a living! Thanks for the hints anyway - I'll get to the bottom of this one way or another :)

**Comment by brentkearney** [comment]
I don't think there is away to do inline attached images with Mailtrain. If someone knows otherwise, please correct me. The images in Mailtrain campaigns need to be referenced as links to externally hosted files. If you use the Mosaico editor, they'll be at, for example https://your.domain/mosaico/uploads/0/yourimage.jpg.

So in a sense, you would "embed" them with a standard image tag in the HTML portion of the email:
`<img src="https://your.domain/mosaico/uploads/0/yourimage.jpg" alt="image" />`

There appears to be no way to do in-line images for attached files, because attached files always get `"Content-Disposition: attachment;...`. If the attachment feature offered an "inline" option, and a Content-Id that we could refer to in the markup, then we could refer to the attached image. i.e.

`<img src="cid:[the content id of the attached image]" alt="image" />`

Another way would be if Mailtrain could "pass-through" an external email, in the way that a traditional mail list functions. Then we could compose the e-mail in a mail client, and send it to Mailtrain for redistribution to a list. This feature doesn't seem to exist, either, however.

**Comment by timelf123** [comment]
```
<img src="cid:[the content id of the attached image]" alt="image" />
```

Is a clean solution. Base64 encoded images are a no-go for emails

**Comment by brentkearney** [comment]
Is there some way to get the content id of attached images, in advance, so that they can be referenced in the HTML portion of an email template?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
