### ISSUE TITLE
V2: Links not wrapped in dynamic campaigns

### ISSUE THREAD

**Issue by ericuldall** [Mailtrain-org/mailtrain#747]
It seems when creating a template from URL, link wrapping is not applied so we are unable to see metrics of what links users are clicking.

Is this a feature or a bug?

**Comment by ericuldall** [comment]
I'd also like some guidance on where to start for a PR here. Please let me know if any current contributors can point me in the right direction to save time digging through superfluous code.

**Comment by bures** [comment]
The original idea was that the external content provider has all the knowledge to update even the links. That's why there was no tag replacement when using URL as content source. In case it is difficult or impossible to generate correct links on the external content provider, we can include it in Mailtrain.

This would however require:
- Ability to specify tag language for URL content - this is a change on the client and migration is needed to to add the "none" tag language to the existing URL-based campaigns where tag language is not specified - see below. (I would like to avoid having this as default option in models/links.js)
- Tag language option "none" that acts as tag language without any replacements. This is for backward compatibility if one wants to avoid any replacement.

Please let me know whether I should proceed with this (or if you want to provide a PR on this). In the former case, I would appreciate some content URL that I could use for testing.

Thanks.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
