### ISSUE TITLE
V2: Make horizontally scalable

### ISSUE THREAD

**Issue by ericuldall** [Mailtrain-org/mailtrain#759]
I think it's an essential feature to make sure this application can scale horizontally. We run all of our applications in kubernetes in order to scale workloads on demand and make sure we use our infrastructure efficiently.

I think we would mainly need to fix the sender process to be stateless and not store any of the message queue or other realtime info in memory. It could be possible to move those stores into redis since the system already supports it.

Even better may be to move the sending process into 2 parts...

**Part 1: Publisher**
Posts messages to redis pub/sub (https://redis.io/topics/pubsub). This process would start when a campaign is scheduled at take all of the subscribers in the list and publish them to redis.

**Part 2: Worker**
This would be a separate application that will subscribe to pub/sub and handle the actual sending of the messages.

Each worker can also be subscribed to some master channel that will tell it the status of a campaign and when it needs to subscribe (on campaign start) or unsubscribe (on campaign end or pause) from a channel.

The good part about modifying the application to work this way is you can scale the sending process (workers) separately from the dashboard code. I think this is ideal since if you're sending 10MM messages, that doesn't put any extra requirements on hosting the dashboard, however you will need to run your sending process in parallel to get a large send done in any reasonable amount of time.

**Comment by bures** [comment]
The sender process is already parallelized via multiple sender workers. Only the sender master is a single point that cannot be parallelized. Are you having performance problems? My experience was that most of the CPU time is spent in workers, DB and Zone MTA. Not in the sender master.

**Comment by ericuldall** [comment]
As of now it seems to work fine with a single pod. However I'm concerned about long term usage...not only in sending but handling a large number of inbound events (clicks, opens,webhooks). This will eventually all add up and the application should be able to run on multiple instances load balanced without issue.

**Comment by bures** [comment]
That's definitely true. At this point it's a bit low on my list because my target is sending to lists of about 100000 subscribers, which the current version handles easily. I believe it cannot be addressed until we have a real deployment that starts having problems with performance. We need the perf. data first before starting to optimize or changing the architecture to scale.

**Comment by ericuldall** [comment]
@bures Can you imagine a way to do this where we run a master enabled version of the application that is a single instance, and then have slave only versions that only run the workers and handle inbound events?

**Comment by bures** [comment]
Yep. That I can imagine. We would however need a two-way synchronisation task that would keep the master and the slaves in sync. And you have to count with the fact that there will be some delay before changes on the master will be visible on slaves and vice versa.

**Comment by ericuldall** [comment]
Are the master process and workers processes kept in sync using only the DB as of now? I'm not sure why moving the worker process into separate instances would change anything. 

> The sender process is already parallelized via multiple sender workers.

Are those sender workers running as separate processes? If so, then they would not have access to any shared memory space and it would be as if they were running on a separate instance already, but perhaps I misunderstood what you meant there.

**Comment by bures** [comment]
It seems there is some confusion around this. Let me explain that in more detail.
The architecture is as follows. There is a sender-master process and multiple sender-worker processes. As nodejs does not have any other means to spawn threads, these are separate processes spawn by the main mailtrain process. You can see it if you type `ps auxf`. They synchronize with the main mailtrain process via DB and via IPC messages. 

After start, mailtrain's main process starts the sender-master, who in turn spawns the sender-workers. When a campaign is to be sent, the main process marks the campaign as scheduled and sends a message to the sender-master to re-check the campaigns (this is not completely necessary, but makes mailtrain swifter). The sender-master lists the subscribers and assigns (in batches) work the sender-workers. The batch typically looks as the campaign id and a list of email addresses to which the campaign is to be delivered.

Another IPC message the sender master reacts to is to refresh the send configurations it caches when a send configuration changes. The sender-master forwards this messages to sender-workers.

The sender-worker (again a separate processes) sends the messages to the emails provided and marks the respective subscribers in DB as completed. 

Though there is only one sender-master, there can be multiple sender-workers. This is configured in the server config.

The IPC between sender-master and sender-workers requires staying on the same machine, but otherwise, it can utilize any number of processors. The sender-master pretty much only coordinates the works among the sender-workers, thus it's not a significant bottleneck. In my experience, the DB starts to be a bottleneck at some point. Thus if one wants to scale horizontally, one has to make the DB scalable. I guess the easiest would be to add another level between the main process and the sender-master. This level would orchestrate work between the main mailtrain and multiple headless mailtrain instances (running on different machines). It would do it by synchronizing/replicating relevant tables. 

As there wouldn't been any tight synchronization among the multiple sender-masters, they would have to pick their workload based on some hashing function over emails (e.g. one takes all subscribers with hash ending with "1", etc.) This would allow scaling arbitrarily, but would make delays (e.g. when you start a campaign or stop it) much longer.

**Comment by ericuldall** [comment]
I think this is a prefect fit for a pub/sub model. Where there can be many subscribers to specific topic. Essentially a topic will get created when a campaign is scheduled and all of the emails to be sent will be published to that topic. Any number of subscribers (workers) can grab messages from the topic and work on them. The pub/sub software will ensure that messages are only delivered once to avoid duplicated work and if the worker is unable to process the message from the queue it can simply return it to the queue for another worker (or itself) to try again.

**Comment by bures** [comment]
I agree. But you would need something rather robust because the pub/sub middleware needs to support some kind of transactions, so that it can cope with workers dying in the middle of their work, etc.

You would also have to distribute the HTTP handler for the public endpoint. Because once the campaign is sent, there is a spike in access the endpoint because of links and pictures. That's why I was suggesting replicating the DB.

**Comment by ericuldall** [comment]
I suppose these are 2 different problems. One is more in regards to sending and the other is in regards to handling inbound traffic.

I agree, adding a couple read replicas to mysql should help with any issues on link clicks and open pixels.

Right now I'm seeing we can send ~4000 messages per hour. I think this is quite slow and i'm running this on a machine with 4 cores and 15GB of RAM (same specs for my SQL instance as well). I was thinking being able to spread out the sending load across more machines would help there (this is where pub/sub would be a fit, essentially replacing IPC). Any tips to increase send speed with different settings perhaps?

At any rate, I think in order to be fully scalable we'll need both a replicated DB and a decentralized messaging system.

**Comment by ericuldall** [comment]
Hi @bures ,

My lists sizes are growing quickly and I'm at the point where my campaigns barely finish in a day. So I'm starting to look into ways to improve performance. One thing I'm starting on is to separate the public endpoint into a separate deployment that can be scaled. Since this is responsible for all the user facing content (links, unsubs, etc...) I think this should work without any major modifications, but let me know if I'm perhaps missing something.

Here's a sample of how I'm trying it right now:
```
async function replicaInit (types) {
    const AppTypeMap = {
      'trusted': AppType.TRUSTED,
      'sandbox': AppType.SANDBOXED,
      'public': AppType.PUBLIC
    };
    const AppPortMap = {
      'trusted': trustedPort,
      'sandbox': sandboxPort,
      'public': publicPort
    };
    for (let type of types) {
      await startHTTPServer(AppTypeMap[type], type, AppPortMap[type]);
    }
    log.info('Service', 'All services started');
    appBuilder.setReady();
}

if (!replicaTypes) {
  init().catch(err => { log.error('', err); process.exit(1); });
} else {
  replicaInit(replicaTypes).catch(err => { log.error('', err); process.exit(1); });
}
```

`replicaTypes` is set from a config like the following:
```
replicaTypes:
- public
- sandbox
- trusted
```
Anything configured in the `replicaTypes` array will start the server for that app. Right now I'm just using it to run a separate public deployment, and since this is a separate deployment I could easily choose to point it to a mysql read replica as well (like you mentioned before).

The only issue I'm having is the Unsubs don't seem to be working in this setup. Everything else works (links, sign up form, preferences, view in browser), but unsubscribing just gets stuck and eventually times out with no errors in the logs (set to silly). Do you have any thoughts on why that's not working? Is there perhaps some other lib I need to run in that replicaInit function?

Any help here would be appreciated.

**Comment by bures** [comment]
Well, I would have too see the whole code and the deployment. It's hard to say this way. 

Anyway, this is an interesting case. Could you share with me (privately if you like) some details regarding your config and workload? I'll be happy to look into it if it helps Mailtrain become better. Like I said before, making something scalable without having a real case is a silly endeavor. Thanks.

**Comment by ericuldall** [comment]
Sure. I'll send an email to the address listed on your profile.

**Comment by bures** [comment]
Great.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
