### ISSUE TITLE
link on button not redirecting to external website

### ISSUE THREAD

**Issue by xufux** [Mailtrain-org/mailtrain#771]
I have added a link to a button on the template (Mosaico)

> https://www.forbes.com/sites/forbestechcouncil/2018/09/17/creating-a-culture-of-compliance-why-all-successful-businesses-must-do-this-and-where-to-begin/#4e9332a55050

![image](https://user-images.githubusercontent.com/23102129/68470818-1d790900-021d-11ea-93dc-786ff9a4c2b3.png)

once the email is received, the link on the button is something like that:

> https://mymailtraindomain/links/XyCmFyvN2/CC4_2JWx8/oeKwvUp8P/RNy3JxF7A

when you click on the link in the email, it opens a mailtrain webpage and the new URL is:

> https://mymailtraindomain/sites/forbestechcouncil/2018/09/17/creating-a-culture-of-compliance-why-all-successful-businesses-must-do-this-and-where-to-begin/#4e9332a55050

as you can see,  the real domain name of my link "www.forbes.com" has been replaced by my mailtraindomain and so it is an error "Not Found".
![image](https://user-images.githubusercontent.com/23102129/68471523-b197a000-021e-11ea-9953-c84f78d1405a.png)

Is this behaviour normal and i must manage a redirect on my mailtrain server or is it a bug ?

**Comment by zeex124** [comment]
I have the same problem can someone answer us please.

In the meantime xufux if you find a solution can you posted it here ? I will do the same.

**Comment by zellnerFinstreet** [comment]
I had the same problem and found the solution:

You have to disable the click-Tracking.

![image](https://user-images.githubusercontent.com/39985620/74014226-898b1a80-498e-11ea-9b7a-3ffaa3ed659c.png)

Otherwise Mailtrain redirects the links to the Mailtrain Instance, tracks the click and the redirects to the original link. In your case there seems to be another issue with Mailtrain redirecting to an incorrect link after tracking, but disabling click-tracking prevents the whole situation.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
