### ISSUE TITLE
Add react-email-editor to templete editors

### ISSUE THREAD

**Issue by andresmrm** [Mailtrain-org/mailtrain#836]
Has anyone thought about adding [react-email-editor](https://github.com/unlayer/react-email-editor) to the template editors? Found no mention to it in the issues.

Has anyone used react-email-editor and agrees it would be a nice addition to Mailtrain? Only tested the demo and seems cool.

Would it be hard to add it to Mailtrain? Any directions on how to start?

Would such PR be accepted?

**Comment by bures** [comment]
As far as I know - NO. 


Indeed, it may be a nice alternative to Mosaico or GrapeJS. However, my experience with users so far is that Mosaico is pretty sufficient. What matters in my view is that one can easily create a custom Mosaico template (this can be done in Mailtrain through Templates->Mosaico templates). I'm not sure if this would be possible the the react-email-editor. 

The problem that Mailtrain has (compared for instance to Mailchimp) is that it does not come with wide variety of ready-to-use graphical templates. This won't be fixed by having yet another email editor. In fact, the ideal case would be to have just one editor, and to have several ready-made styles (e.g. Mosaico templates).

Another problem with this editor is that it's not open-source. It's a paid service wrapped by an open source component. I would like to avoid having such things in Mailtrain.

**Comment by andresmrm** [comment]
Thanks for the quick replies!

> Another problem with this editor is that it's not open-source. It's a paid service wrapped by an open source component. I would like to avoid having such things in Mailtrain.

Sorry, didn't notice it. I should have checked the code in that repository and would have seen there is almost nothing there. :man_facepalming:
