### ISSUE TITLE
v2 - multiple Google Analytics tracking IDs

### ISSUE THREAD

**Issue by Malm** [Mailtrain-org/mailtrain#898]
Hi,
First of all - very nice work with Mailtrain! 

Is it possible to add multiple GA tracking IDs, e.g specify a GA Tracking ID per list in order to track clicks etc across multipel GA properties.

**Comment by bures** [comment]
Thanks. What you suggest makes perfect sense. I think it would make sense to associate it with a send configuration as the contains other this related to the sender.  List is another candidate, though maybe not so practical because a campaign may send to multiple lists.

Do you have any capacity/expertise on your side to implement this? I'll be happy to accept the PR and possibly help with pointing you to the right place.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
