### ISSUE TITLE
Conditional Merge Tags

### ISSUE THREAD

**Issue by OutplayCity** [Mailtrain-org/mailtrain#908]
Hi everyone,

is there a guide, wikipage or blog that can help me with conditional merge tags in mailtrain?
I'm used to merge tags in mailchimp, but unfortunately it's seems quite difficult to integrate merge tags in mailtrain.

Thanks in advance
Lars

**Comment by bures** [comment]
Mailtrain v1 or v2?

**Comment by OutplayCity** [comment]
> Mailtrain v1 or v2?

I'm not quite sure, beacause I'm logging in via news.daasi.de and use my external Loging from LDAP. Where can I find the information about the used version?

**Comment by bures** [comment]
That's v1. I'm afraid the options here are limited. As far as I know, you can only specify the default value to be used if a tag is not present.

**Comment by OutplayCity** [comment]
> That's v1. I'm afraid the options here are limited. As far as I know, you can only specify the default value to be used if a tag is not present.

Has v2 the option to implement conditional merge tags? Since we use Mosaico and html could gives us more opportunities, would you recommend using GrapeJS instead? Or does GrapeJS not have the option to use conditional merge tags?

My workaround now would be that I create campaigns for each segment

**Comment by bures** [comment]
In v2, you can choose Handlebars (https://handlebarsjs.com/) as the tag language. It is independent of what editor you choose. However, in order to fully leverage them, you will have to go either for HTML/MJML or create your own Mosaico template. Generally, I would recommend MJML or a custom MJML Mosaico template. HTML for emails is in my view too cumbersome.

**Comment by OutplayCity** [comment]
Alright, I'll look out for it. Thank you for your help 💪
