### ISSUE TITLE
Automation/triggers - custom fields on list contact, update field via API

### ISSUE THREAD

**Issue by Nowaker** [Mailtrain-org/mailtrain#92]
We currently use Customer.io and Knowtify.io for behavioral emails, engagement and upsell marketing and MailChimp for typical newsletters. We don't like the current state because each system lives by its own, holds its own data, and data flow is limited. I had a look at Mailtrain out of curiosity - I didn't really think seriously about it. But this got me a jaw drop:

![image](https://cloud.githubusercontent.com/assets/611746/18465466/446fdeba-7997-11e6-9c63-d4fab1972fd4.png)

I was like, jeeez, newsellter can no longer be a black box! And we can send follow-ups based on activity! And we can also get rid of Customer.io and Knowtify!

For this to actually happen, there's a need for custom fields that hold state on a user (contact on a list). For example, if a customer signs up for Virtkick on day 1, we push info about this user to Customer.io via API (setup_1 = false, setup_2 = false, setup_3 = false). When customer performs the first step in setup, we update Customer.io (setup_1 = true, setup_2 = false, setup_3 = false). A rule of thumb is any action that matters is reported to Customer.io so that the rules engine can decide what email, if any, should be sent to the customer.

Have you ever thought about this?

**Comment by andris9** [comment]
You can achieve part of this with (non-visible) custom fields and the current API where you can update a specific field value but you can only create segments out of this information (eg. a segment with rule "checkbox Step1 must be selected") but you can't use it as input for automated trigger based sending.

Actually I had in mind creating a more powerful automation support that would have allowed you to achieve what you described and even more, like also modifying user state with triggers (think of "3 days after signup set the value of X as Y" or "if rule X matches then move subscriber from one list to another"), so I ran a [crowdfunding campaign](https://www.indiegogo.com/projects/mailtrain-self-hosted-newsletter-app--2#/) in spring to be able to allocate time for it but the campaign failed and I had to take another job so for now I am able to maintain Mailtrain, fix bugs, add small features etc. but don't have time for anything substantial.

**Comment by Nowaker** [comment]
I see. If I provided a PR where these could be used as triggers, would you accept it?

The "powerful automation" you mention sound good too. It's a common practise to move a lead to a regular mailing list after a lead dropped during the checkout process and 3 or 5 subsequent follow-ups didn't result in a purchase.

I'm wondering how you view users/emails in Mailtrain. Is email an object on the list, meaning there are two different (by their identity) objects on two lists, or is there one uber-object that belongs to zero, one or many lists? I'm generally concerned about data retention. If I move email from one list to another, all history data should be retained. When I add this email to a second list, this email should still have the same identity. If I remove the email from the list, it should still stay in the system - just not be present on any list.

Thanks.

**Comment by andris9** [comment]
Yes, PR's are welcomed and usually get merged.

My idea on moving a subscriber from one list to another was actually copying the data and marking the user as moved in the original list with a reference to the new list. This was also needed to keep the older "unsubscribe" and "profile settings" links working that contain list and subscriber ids. As a comparison when a user unsubscribes or bounces the data does not get deleted, the user gets marked as unsubscribed and does not get any mail but the data is still there, otherwise it would break existing links and statistics.

I didn't really think about the option of having the same subscriber in multiple lists at first, so I'm not sure how this would work out, the data model expects to have a single active list for a subscriber (every list has it's own database table). I guess this could be changed though by adding a new table that contains links between subscribers in different tables, so for example when updating a name it would seek out the same user in other lists and make the same update in these tables as well.
